### ISSUE TITLE
Add WebM (VP8) playback support

### ISSUE THREAD

**Issue by brion** [brion/ogv.js#10]
So far I've concentrated on Ogg format, but it'd be good to get WebM going as well. Should compare performance and picture quality...

This requires pulling in more C libraries: libwebm for the Matroska-based container, and libvpx for the VP8 codec. Some of these may be C++ so need to look into this in more detail.

Also note that on Commons we generally have Theora transcodes at only 480p unless the original file is smaller than that; whereas for WebM we already have 360p transcodes made. That's about 45% fewer pixels to process, which is likely going to be a big performance win on slower devices.

**Comment by brion** [comment]
Currently in progress on webm-experimental branch. VP8 is definitely a lot slower than Theora but it gives much better picture quality. We'll see what can be further optimized... :D

**Comment by maikmerten** [comment]
Microsoft Edge appears to have experimental SIMD support. Depending on what operations are specified and implemented for what data types, this could be useful. Not sure what specification they're implementing, though, and thus no idea if this matches emscripten's intrinsics for SIMD.

(of course, this would also be useful for Theora, but is clearly more important for VP8)

**Comment by brion** [comment]
Edge does fairly well with the asm.js optimizations enabled but probably can do a lot better with SIMD, will have to experiment with that... -> https://github.com/brion/ogv.js/issues/124

**Comment by brion** [comment]
Still experimental but landed on master a whiles ago. See milestone for detail issues now
