### ISSUE TITLE
Audio doesn't play in iOS

### ISSUE THREAD

**Issue by bvibber** [brion/ogv.js#14]
In iOS, WebAudio must be initialized in a user-initiated event handler or it's forced to mute. Currently this doesn't happen for two reasons:
- we play automatically (not in response to a user event)
- we don't initialize audio until after asynchronous data input and processing comes back with the presence of an audio track (not a user input event, so it may not count)

**Comment by goffi-contrib** [comment]
Hello @brion , I've found this old ticket as I have no sound using an old iPhone 5s, this is also happening with the demo at https://brionv.com/misc/ogv.js/demo/ . Is this platform still supported? Is there any specific option to activate? Thanks!
