### ISSUE TITLE
make js error. I need your help.

### ISSUE THREAD

**Issue by steveboks** [brion/ogv.js#162]
Hi, Brion
I'm Bokseong KIM. in Korea

There was an issue during OGV.js installation, I needed your help.
make js command is error.
Don't make 'build/js/ogv-libs.js' file
what's problem?

make js error
------
root@ubuntu:/home/labo/ogv.js# make js
test -d build || mkdir build
./compileOgvJs.sh
WARNING  root: (Emscripten: system change: 1.10.0|le32-unknown-nacl|/root/emsdk_portable/clang/fastcomp/build_master_64/bin|3.6.0 vs 1.31.0|asmjs-unknown-emscripten|/root/emsdk_portable/clang/fastcomp/build_master_64/bin|3.6, clearing cache)
WARNING  root: LLVM version appears incorrect (seeing "3.6.0", expected "3.2")
INFO     root: (Emscripten: Running sanity checks)
/root/emsdk_portable/clang/fastcomp/build_master_64/bin/lli: error creating EE: No available targets are compatible with this triple, see -version for the available targets.
FAIL: Running the generated program failed!
Traceback (most recent call last):
  File "/usr/bin/emcc", line 1864, in <module>
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/usr/share/emscripten/tools/shared.py", line 1276, in emscripten
    assert os.path.exists(filename + '.o.js') and len(open(filename + '.o.js', 'r').read()) > 0, 'Emscripten failed to generate .js: ' + str(compiler_output)
AssertionError: Emscripten failed to generate .js: 
make: *** [build/js/ogv-libs.js] error 1

This is a problem?
the codes below path in accordance with version looks different.
-----------------
root@ubuntu:~# emcc -v
emcc (Emscripten GCC-like replacement + linker emulating GNU ld ) 1.10.0
clang version 3.6.0 (https://github.com/kripken/emscripten-fastcomp-clang/ 1e87fd50b108143298407eb4b9a802cea4662937) (https://github.com/kripken/emscripten-fastcomp/ cb8b737f3d49e9edd214d5214db6ace92b5e68ea)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Selected multilib: .;@m64

-----------------
root@ubuntu:~/emsdk_portable/emscripten/master# ./emcc -v
WARNING  root: (Emscripten: system change: 1.31.0|asmjs-unknown-emscripten|/root/emsdk_portable/clang/fastcomp/build_master_64/bin|3.6 vs 1.10.0|le32-unknown-nacl|/root/emsdk_portable/clang/fastcomp/build_master_64/bin|3.6.0, clearing cache)
INFO     root: (Emscripten: Running sanity checks)
emcc (Emscripten GCC-like replacement + linker emulating GNU ld ) 1.31.0
clang version 3.6.0 (https://github.com/kripken/emscripten-fastcomp-clang/ 1e87fd50b108143298407eb4b9a802cea4662937) (https://github.com/kripken/emscripten-fastcomp/ cb8b737f3d49e9edd214d5214db6ace92b5e68ea)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Selected multilib: .;@m64
INFO     root: (Emscripten: Running sanity checks)
root@ubuntu:~/emsdk_portable/emscripten/master#

**Comment by brion** [comment]
(going through unclosed bugs)...

It kinda looks like you've got a mix of emscripten versions installed; perhaps an update didn't get fully activated and there's old paths still in your environment?
