### ISSUE TITLE
How can i jump to a specific time in the video.

### ISSUE THREAD

**Issue by chaitanyapro** [brion/ogv.js#165]
Is there any API available to jump to a specific part in the video. If not can you please suggest me an alternative. :)

**Comment by brion** [comment]
You should be able to assign a time in seconds to the currentTime property to trigger a seek. This may or may not work properly for setting a start point before playback, but should definitely work for seeking during playback. Give a shout if any surprises. :)

**Comment by chaitanyapro** [comment]
That's cool I'll give it a try. Thanks :)
