### ISSUE TITLE
Error: Uncaught Error: called dequeueAudio when no audio ready

### ISSUE THREAD

**Issue by ghost** [brion/ogv.js#169]
I'm trying to autoplay the video, but this is what I get in my console.

Uncaught Error: called dequeueAudio when no audio ready

**Comment by brion** [comment]
Can you provide a sample page to test?

**Comment by chaitanyapro** [comment]
So basically I want to autoplay a video. It's working fine when the video is played using a click event. Also  can you please tell me what are the required video specifications (Frame Rate etc.) Because one of my .ogv video is not working it just shows the first frame.

**Comment by chrislearn** [comment]
I want the video can autoplay in mobile device, it seems if the ogv file contains audio, it can not autoplay, if I remove audio from the ogv file, it can autoplay.

**Comment by chaitanyapro** [comment]
Okay can you please tell me how to convert the video i mean mine is not working it just shows the first frame that's it.

**Comment by brion** [comment]
Autoplay with audio is not possible on iOS; the audio *must* be started from a user input event handler or it simply doesn't work. :(

**Comment by chaitanyapro** [comment]
Okay that's fine! can you please tell me how to convert the video? I converted the video and it's not working it just shows the first frame.

**Comment by brion** [comment]
merging into https://github.com/brion/ogv.js/issues/112
