### ISSUE TITLE
Error with make js (Linux)

### ISSUE THREAD

**Issue by dudewheresmycode** [brion/ogv.js#170]
When I run the `make js` command, it all seems to work up until this error. I've confirmed I have the dependencies installed and up to date. Any ideas? Running an Ubuntu 14.04.2 LTS instance on DigitalOcean.

```console
test -d build || mkdir build
./compileOgvJs.sh
ERROR    root: build/js/root/lib/libogg.so: No such file or directory ("build/js/root/lib/libogg.so" was expected to be an input file, based on the commandline arguments provided)
make: *** [build/js/ogv-libs.js] Error 1
```

**Comment by dudewheresmycode** [comment]
Actually reinstalling emscripten now, figuring this is probably where the issue lies.

**Comment by dudewheresmycode** [comment]
So even after a fresh emscripten install. I'm getting a input file error.

````console
brian@addroid-main:/var/www/html/addroid-qa-com/labs/ogv/git/ogv.js$ emcc -v
emcc (Emscripten gcc/clang-like replacement) 1.33.0
clang version 3.7.0 (https://github.com/kripken/emscripten-fastcomp-clang/ 2a66b5ffba63f1e36458d41fafc2874a1abf63fe) (https://github.com/kripken/emscripten-fastcomp/ e2939f6878307899c17d1a23f51ba3fe5afbe6af)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Selected multilib: .;@m64
INFO     root: (Emscripten: Running sanity checks)
````

I'm also getting a few errors in the make command like:

````
checking if /var/www/html/addroid-qa-com/labs/ogv/git/emsdk_portable/emscripten/master/emcc supports -c -o file.o... yes
checking if /var/www/html/addroid-qa-com/labs/ogv/git/emsdk_portable/emscripten/master/emcc supports -c -o file.o... (cached) yes
checking whether the /var/www/html/addroid-qa-com/labs/ogv/git/emsdk_portable/emscripten/master/emcc linker (/var/www/html/addroid-qa-com/labs/ogv/git/emsdk_portable/emscripten/master/emcc) supports shared libraries... no
checking dynamic linker characteristics... ERROR    root: no input files
note that input files without a known suffix are ignored, make sure your input files end with one of: ('.c', '.C', '.i', '.cpp', '.cxx', '.cc', '.c++', '.CPP', '.CXX', '.CC', '.C++', '.ii', '.m', '.mi', '.mm', '.mii', '.bc', '.o', '.obj', '.dylib', '.so', '.a', '.ll', '.h', '.hxx', '.hpp', '.hh', '.H', '.HXX', '.HPP', '.HH')
GNU/Linux ld.so
checking how to hardcode library paths into programs... unsupported
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... no
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking GCC version... ERROR    root: no input files
note that input files without a known suffix are ignored, make sure your input files end with one of: ('.c', '.C', '.i', '.cpp', '.cxx', '.cc', '.c++', '.CPP', '.CXX', '.CC', '.C++', '.ii', '.m', '.mi', '.mm', '.mii', '.bc', '.o', '.obj', '.dylib', '.so', '.a', '.ll', '.h', '.hxx', '.hpp', '.hh', '.H', '.HXX', '.HPP', '.HH')

````

**Comment by brion** [comment]
Hmm, might be a regression on newer emscripten, lemme take a quick check.

**Comment by brion** [comment]
Ok I can confirm this behavior on Ubuntu 14.04 with emscripten master (1.33) installed from source via the SDK.

Will double-check with master on Mac OS X (where I've been using emscripten 1.30 from the SDK's binary install) to see whether it's a Linux thing or a regression. Whee!

**Comment by brion** [comment]
Ok, I don't have the problem with emscripten master on OS X, so the regression may be hitting Linux only. I'll try and track it down if I can...

**Comment by brion** [comment]
Tracked it down, it's a regression in emscripten's hacks for using autoconf build systems. Pull req submitted: https://github.com/kripken/emscripten/pull/3538

**Comment by chrislearn** [comment]
I use ubuntu 15.04 and I have the same error, even I updated the emcc file in emscripten, changed the line 167:
# Note: removing 'GNU' in the line below will break some autoconf projects'
  # ability to build shared libraries on Linux hosts; libtool's configure script
  # add-in checks for it.
  print '''emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) %s (%s)

**Comment by brion** [comment]
You'll need to wipe out the old build files; do a 'make clean' then 'make' and hopefully it should come back better, stronger, workinger. :D

**Comment by chrislearn** [comment]
@brion Thanks for your reply, but 'make clean' is not working for me. I create a screen capture, can you help me to find what wrong with it?
https://www.youtube.com/watch?v=_UPt-oqaOn4

**Comment by brion** [comment]
Hmm can you do 'emcc --version' and see if the 'GNU' shows up in there? (-v and --version seem distinct for extra fun)

**Comment by chrislearn** [comment]
![s](https://cloud.githubusercontent.com/assets/5874864/8149354/db308474-12f2-11e5-9354-1300304bd1f3.png)

**Comment by brion** [comment]
*headdesk* I messed up that patch. the 'GNU ld' bit belongs on the '-v' output not on the '--version' output. (This is probably why Alon keeps nudging me to include test cases! ;)

**Comment by brion** [comment]
Ok I updated the patch for emscripten to the correct version; re-apply and it should work.

**Comment by chrislearn** [comment]
Still can not work...
![emcc](https://cloud.githubusercontent.com/assets/5874864/8150648/4d7172d8-1324-11e5-9177-fbb9b7794de4.png)
![v](https://cloud.githubusercontent.com/assets/5874864/8150649/4d741394-1324-11e5-8871-83d22bf67519.png)

**Comment by brion** [comment]
You seem to be missing both the old and new patch to emcc?

**Comment by chrislearn** [comment]
Oh..., Sorry, it worked now. Thanks!

**Comment by chrislearn** [comment]
But there is another error when compile compileWebMJs.sh

![x](https://cloud.githubusercontent.com/assets/5874864/8150968/6e3b6e1c-1331-11e5-9810-b43aa08882a8.png)

**Comment by brion** [comment]
Hmmm, are you missing the libvpx submodule checkout? Make sure it's there, and do a 'git submodule update --init' if necessary to re-add it.

**Comment by chrislearn** [comment]
@brion You are right, I'm in china so the libvpx repository can not access and I did not notice this error.
