### ISSUE TITLE
WebM aspect ratio issue with Xylocopa video

### ISSUE THREAD

**Issue by brion** [brion/ogv.js#174]
The file '[Xylocopa violacea male - 2012-10-23.webm](https://brionv.com/misc/ogv.js/demo/#file=Xylocopa_violacea_male_-_2012-10-23.webm&size=360p.webm)' seems to have some aspect ratio funkiness; the resulting output with WebM original and transcodes is squished and has lots of junk in the image.

Probably not handling image cropping correctly with WebM.

![screenshot 2015-06-23 04 08 30](https://cloud.githubusercontent.com/assets/103075/8304754/bd5e5acc-195d-11e5-9f81-efd12cb59daf.jpg)

**Comment by Yay295** [comment]
For clarity, I am going to split the image into three parts:
1. The part that looks like a video.
2. The thin column of junk.
3. The thick column of junk on the right.

It looks to me like part 1 has been squished to the left, part 2 is the rightmost column of pixels from the video, slightly stretched, and I think part 3 is the leftmost column of pixels from the video, very stretched and on the wrong side.

Here's two images taken at roughly the same time. The first is this video played as WebM, and the second is this video played as Ogg.

![screen shot 06-23-15 at 07 55 pm](https://cloud.githubusercontent.com/assets/8922038/8320635/108d5db2-19e3-11e5-94c0-df73eac5f63d.PNG)
![screen shot 06-23-15 at 07 55 pm 001](https://cloud.githubusercontent.com/assets/8922038/8320636/109b9e5e-19e3-11e5-92a7-978c565da111.PNG)
