### ISSUE TITLE
npm package for browser

### ISSUE THREAD

**Issue by brion** [brion/ogv.js#184]
Once have dist releases, make an npm package for browser apps. Look up best practices on packaging.

**Comment by hartman** [comment]
FYI, this one is higher on my interest list now for both TMH and the @hartman/videojs-ogvjs#2

**Comment by brion** [comment]
My current inclination is to tweak the build process like this:
* build the emscripten'ized .js modules into predictable location (build/assets? asssets/emscripten?)
* make sure that part of the build output _is_ included via 'npm publish'
* use some webpack magic to pack up the module .js files from that assets subdir into either the dist build or caller's webpack output without having to duplicate the copy logic
 * if can't figure a cleaner way to do it, reference them in via file-loader plugin like for the .swf in audio-feeder

That should allow webpack-using callers to just toss 'ogv' into their dependencies have the modules appear in a sensible directory, without having to worry about the C->JS emscripten side of the build process... and tarball/zip release of the dist files would still be suitable for people using their own build systems.

**Comment by brion** [comment]
done a8dbd0d -> https://www.npmjs.com/package/ogv
