### ISSUE TITLE
Vorbis decoder failed mysteriously

### ISSUE THREAD

**Issue by Marc477** [brion/ogv.js#196]
It is impossible to read .ogv file encoded with ffmpeg, i tried thoses commands:

ffmpeg -i bunny.mp4 -t 60 -s 426x240 -vcodec libtheora -r 12 -b:v 100k -g 24 -acodec libvorbis -b:a 80k -ar 44100 -ac 2 -f ogg -y bunny.ogv

or

ffmpeg -i bunny.mp4  -y bunny.ogv

And when I try to play the file with ogv.js, i get the error: Vorbis decoder failed mysteriously? -135

What is wrong?  I have no problem with WebM (they use vorbis too). But since I cannot seek with webm file. I would prefer a seekable format.

Thank you

**Comment by Marc477** [comment]
ffprobe result, if it can help:

Demo video (working)
Input #0, ogg, from 'test.ogv':
  Duration: 00:03:59.85, start: 0.000000, bitrate: 543 kb/s
    Stream #0:0: Data: none
    Stream #0:1: Video: theora, yuv420p, 640x360 [SAR 1:1 DAR 16:9], 23.98 tbr,
23.98 tbn, 23.98 tbc
    Metadata:
      ENCODER         : ffmpeg2theora-0.27
      SOURCE_OSHASH   : 960940fbca5de646
    Stream #0:2: Audio: vorbis, 44100 Hz, stereo, fltp, 80 kb/s
    Metadata:
      ENCODER         : ffmpeg2theora-0.27
      SOURCE_OSHASH   : 960940fbca5de646
Unsupported codec with id 0 for input stream 0

Encoded with ffmpeg (not working)
Input #0, ogg, from 'bunny.ogv':
  Duration: 00:01:00.00, start: 0.000000, bitrate: 291 kb/s
    Stream #0:0(und): Video: theora, yuv420p, 640x360 [SAR 1:1 DAR 16:9], 24 fps
, 24 tbr, 24 tbn, 24 tbc
    Metadata:
      LANGUAGE        : und
      HANDLER_NAME    : VideoHandler
      ENCODER         : Lavc56.21.102 libtheora
      MAJOR_BRAND     : isom
      MINOR_VERSION   : 512
      COMPATIBLE_BRANDS: isomiso2avc1mp41
    Stream #0:1(und): Audio: vorbis, 48000 Hz, stereo, fltp, 112 kb/s
    Metadata:
      LANGUAGE        : und
      HANDLER_NAME    : SoundHandler
      ENCODER         : Lavc56.21.102 libvorbis
      MAJOR_BRAND     : isom
      MINOR_VERSION   : 512
      COMPATIBLE_BRANDS: isomiso2avc1mp41

**Comment by brion** [comment]
Can you post the sample file? I'll throw it in the debugger and see...

**Comment by Marc477** [comment]
I uploaded the file here:
http://www.filedropper.com/bunny

THank you

**Comment by Marc477** [comment]
After the error mentionned above, I also get the error: called deQueue audio when no audio is ready

**Comment by brion** [comment]
That link redirects me to the main page of the site, no file to download.

**Comment by brion** [comment]
Ok, I can reproduce this error with the given ffmpeg command-line params using http://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_640x360.m4v as input. Investigating...

**Comment by brion** [comment]
Ok, give a shout if the error remains after that!

**Comment by Marc477** [comment]
Cool !
