### ISSUE TITLE
webgl render issue

### ISSUE THREAD

**Issue by chrislearn** [brion/ogv.js#197]
I create a demo, same video, but if I set option webGL=true, the bottom of the video looks strange.
http://test.rto.im/ogv/intro.html
http://test.rto.im/ogv/intro-webgl.html

![x](https://cloud.githubusercontent.com/assets/5874864/8468749/ad03367e-20a2-11e5-93a3-2c6b5edd1205.jpg)

**Comment by brion** [comment]
Interesting, the crop positioning seems wrong. I'll take a peek...

**Comment by brion** [comment]
Thanks for the bug report!
