### ISSUE TITLE
autodetect base dir from script src path if possible

### ISSUE THREAD

**Issue by brion** [brion/ogv.js#246]

**Comment by avgeorge** [comment]
Auto-detect fails if scripts are at the root e.g.
`<script src="ogv.js"></script>`

`defaultBase()` returns undefined which results in requests to incorrect URLs such as `http://localhost:8085/undefinedogv-demuxer-ogg.js`

The [current regex](https://github.com/brion/ogv.js/blob/9edead39d91c5b39dedec3eeec8f21dfa6381047/src/js/OGVLoader.js#L87) expects at least one '/' before the script name, which causes the failure in the above case.
