### ISSUE TITLE
IE/Edge scale non-square-aspect-ratio files jaggedly using WebGL

### ISSUE THREAD

**Issue by brion** [brion/ogv.js#277]
Switching back to the stripe texture for IE/Edge speeds up WebGL drawing significantly due to the slow upload of non-RGBA textures, but it disables the antialiasing on the texture.

This has no effect on files with square pixels because we draw 1:1 into the canvas, which is then scaled to the desired output size... but on files with non-square pixel aspect ratio, we have a canvas at the square-pixel-equivalent display size and draw into it, which can create jaggies for instance on Xylocopa WebM version:

https://brionv.com/misc/ogv.js/demo2/#file=Xylocopa_violacea_male_-_2012-10-23.webm&search=jarry&size=360p.webm

![xylocopa edge vs firefox](https://cloud.githubusercontent.com/assets/103075/8856343/0fde810e-311f-11e5-8e3f-2b2e77d460b1.JPG)

**Comment by patrickkettner** [comment]
Hey @brion! I work on Edge and just wanted to let you know that I reported this internally and we are working on it.

Thanks a ton for listing the issue so we can find it :D

**Comment by hartman** [comment]
@patrickkettner :thumbsup:

**Comment by brion** [comment]
On further investigation, it looks about the same on Mac OS X without the stripe texture stuff if I use gl.NEAREST as the mag filter... nearest neighbor just looks awful. ;)

I think the thing to do is to do some rendering into frame buffers so can do the unpacking in one step (no texture filtering) and then the YUV-RGB blit in the second (with linear filtering).

**Comment by brion** [comment]
Ended up just removing the stripe optimization, it's a pain in the butt for relatively little benefit.

Note that artifacting seemed worse with Intel GPUs than with NVidia GPUs. Could be a difference in how they handle nearest-neighbor sampling at funky boundaries.

**Comment by brion** [comment]
Actually ended up retooling the stripe unpacking as a separate render step, it's all much cleaner now. :)
