### ISSUE TITLE
Support 'timeupdate' event

### ISSUE THREAD

**Issue by brion** [brion/ogv.js#298]
Required for subtitles in MediaWiki's TimedMediaHandler

full event list of doom - https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Media_events

**Comment by brion** [comment]
note: worked around this using framecallback for now, but should still add

**Comment by hartman** [comment]
I just ran into a similar problem with durationchange not being triggered after the duration becomes known.

**Comment by Sneagan** [comment]
Hitting this as well. Could you post the workaround for the mean time?
