### ISSUE TITLE
Is there a way to disable audio and let video autoplay

### ISSUE THREAD

**Issue by chrislearn** [brion/ogv.js#302]
I know without user action, audio can not play in ios. But sometimes I only want the video autoplay first time without audio, after user action, the video will replay with audio enabled.
I add the code to demo/minimal.html, the player can not play video, is there anyway to implement this?
```javascript
window.addEventListener('load', function(){
	play(sampleFile);
}, false)
```

**Comment by brion** [comment]
Merging into https://github.com/brion/ogv.js/issues/112
