### ISSUE TITLE
`liboggz.dylib` Missing

### ISSUE THREAD

**Issue by Sneagan** [brion/ogv.js#306]
Everything else appears to be configured correctly, but I'm getting  this error from `make js`:

`ERROR    root: build/js/root/lib/liboggz.dylib: No such file or directory ("build/js/root/lib/liboggz.dylib" was expected to be an input file, based on the commandline arguments provided)`

**Comment by brion** [comment]
Are you building on Mac OS X or Linux? If Mac, then something's probably going wrong in the liboggz build and it's not succeeding as expected. If Linux, then something else is wrong as it should be looking for a '.so' :)

If on Mac -- can you do a 'make clean', then a 'make build/js/root/lib/liboggz.a' and attach a log of the complete output?

**Comment by brion** [comment]
^ ok that latest fix to the Makefile will likely help. :)

**Comment by Sneagan** [comment]
That was fast. Thanks!
