### ISSUE TITLE
iOS9

### ISSUE THREAD

**Issue by cwbeck** [brion/ogv.js#310]
So Apple has decided to remove the ability to access audio context without a full-click to initiate the player. Anybody hoping to use any other events (swipe, scroll, etc) or autoplay is going to have an issue. This works in current release iOS 8.4, but in iOS 9.1 you will need to add more logic to ensure you have access to audio context otherwise player will only load first frame and freeze.

Not been able to find a workaround for this.

**Comment by mattiasmak** [comment]
If the player can't access to the audio context, audio should be ignored but video played instead and periodically check for audio access. That way a video could autoplay but will be muted until the user clicks. Possible?

**Comment by brion** [comment]
Merging related issues into parent issue: https://github.com/brion/ogv.js/issues/112
