### ISSUE TITLE
Trying to Use ogv.js Element as WebGL Video Texture

### ISSUE THREAD

**Issue by Sneagan** [brion/ogv.js#311]
Working through this now using Three.js. Audio is coming through but the video isn't coming in as a texture. Is there a way I can hook into the ogv.js WebGL texture directly and modify it?

**Comment by brion** [comment]
You should be able use the canvas element that sits inside the ogvjs element as a texture source. Currently the canvas is not exposed as a property, but you should be able to use querySelector to get it:

```
  var mySourceCanvas = myOgvjs.querySelector('canvas');
  gl.texImage2D(/* ... params ... */, mySourceCanvas);
```

Untested but should work. :D

**Comment by Sneagan** [comment]
Great. Will try. Thanks!

**Comment by Sneagan** [comment]
Works like a charm
