### ISSUE TITLE
Demo missed the lib folder

### ISSUE THREAD

**Issue by xzf158** [brion/ogv.js#314]
I didn't successfully configure the build environment on my computer, can your submit the lib folder to git.
<img width="795" alt="screen shot 2015-09-23 at 11 31 48" src="https://cloud.githubusercontent.com/assets/702785/10037317/0502dd04-61e7-11e5-8413-0ef35154bc40.png">

**Comment by brion** [comment]
You can download the 1.0 release .zip at https://github.com/brion/ogv.js/releases/tag/1.0
