### ISSUE TITLE
Fixed some random crashes in ogv.js

### ISSUE THREAD

**Issue by Marc477** [brion/ogv.js#315]
I experienced some random crashes when changing the src (player.src) more then 3-4 times in the same page. This would happens sometimes on my PC (after 6-10 src switch), and very ofter on the iphone (only 2-3 src switch).

Usually, this is not a problem on the PC since the javascript wont stop running. But on the iphone it seems like everything stops running when there is a javascript error.

I think I fixed it by adding some validations in ogv.js. Not sure if it is the best way to fix it:

Line 3260:
Error: Uncaught TypeError: Cannot read property 'frameBuffer' of null

    if (ok) {
        // Save the buffer until it's time to draw
        yCbCrBuffer = codec.frameBuffer;
    } else {
        // Bad packet or something.
        log('Bad video packet or something');
    }

Changed to: (added: "&& codec")

    if (ok && codec) {
        // Save the buffer until it's time to draw
        yCbCrBuffer = codec.frameBuffer;
    } else {
        // Bad packet or something.
        log('Bad video packet or something');
    }

Line 3289
Error: Uncaught TypeError: Cannot read property 'audioBuffer' of null

    if (ok) {
        var buffer = codec.audioBuffer;
        if (buffer) {
            // Keep track of how much time we spend queueing audio as well
            // This is slow when using the Flash shim on IE 10/11
            bufferTime += time(function() {
                audioFeeder.bufferData(buffer);
            });
            audioBufferedDuration += (buffer[0].length / audioInfo.rate) * 1000;
        }
    }

Added && codec there too:

    if (ok && codec) {
        var buffer = codec.audioBuffer;
        if (buffer) {
            // Keep track of how much time we spend queueing audio as well
            // This is slow when using the Flash shim on IE 10/11
            bufferTime += time(function() {
                audioFeeder.bufferData(buffer);
            });
            audioBufferedDuration += (buffer[0].length / audioInfo.rate) * 1000;
        }
    }

Line 2939 (function doProcessing)

    if (isProcessing()) {
        // Called async while waiting for something else to complete...
        // let it finish, then we'll get called again to continue.
        return;
    }

Becomes:

    if (isProcessing() || !codec) {
        // Called async while waiting for something else to complete...
        // let it finish, then we'll get called again to continue.
        return;
    }

**Comment by Marc477** [comment]
One more: line 795 ogv.js : Uncaught TypeError: Cannot read property 'length' of null

    function popNextBuffer() {
        // hack hack
        // fixme: grab the right number of samples
        // and... rescale 
        if (buffers.length > 0) {
            return buffers.shift();
        }
    }

Changed to 

    function popNextBuffer() {
        // hack hack
        // fixme: grab the right number of samples
        // and... rescale 
        if (buffers && buffers.length > 0) {
            return buffers.shift();
        }
    }

**Comment by brion** [comment]
Thanks, I'll do a pass over these and double-check if they need higher-level fixes too!

**Comment by brion** [comment]
Ok, 9ee6894 should prevent these from happening in the first place by terminating the worker threads, preventing any pending callbacks from making it back to the parent context after switching sources.
