### ISSUE TITLE
How do I play the next video in the same player?  

### ISSUE THREAD

**Issue by gitfu** [brion/ogv.js#317]
This is what I'm doing now,
```
function playvideo(oplayer, videosrc){
                oplayer.src=videosrc
                oplayer.load()
               oplayer.play()
}
```
Is there a better way?

(Sorry for all the edits, I'm still half asleep )

**Comment by brion** [comment]
Should work to do:

```
oplayer.src = videosrc;
oplayer.load();
oplayer.play();
```

**Comment by brion** [comment]
Ah that's what you're doing. :) I believe this is correct yes.

**Comment by brion** [comment]
Looks like this is not always reliable -- duping to issue https://github.com/brion/ogv.js/issues/334
