### ISSUE TITLE
Background audio regression: stuttering on audio-only files in Safari

### ISSUE THREAD

**Issue by brion** [brion/ogv.js#318]
Downstream bug w/ details: https://phabricator.wikimedia.org/T115241

Probably an issue with throttled timers and whatnot.

**Comment by hartman** [comment]
This is an awesome piece on these kinds of challenges btw:
http://www.html5rocks.com/en/tutorials/audio/scheduling/

**Comment by brion** [comment]
Nice read. :)

ogv.js currently does its processing checkins on a few different bases:
1. when we're stalled on data input, we wait for an event from the source XHR
2. when we're stalled on codec output, we wait for an event from the worker
3. if we still have data to process, we just keep looping through via a scary-ass tail call
4. when we have some time yet before the next frame display or audio buffering, we schedule a timer

Number 4 is probably where we're getting throttled.

With Web Audio, we get that audioprocessing event coming in regularly even when in the background, but we're only sending that event on to OGVPlayer's loop if we were *completely* out of buffered data... at which point we're going to have to wait for further decoding to happen asynchronously so we're probably guaranteed an audio glitch. And then further something's dropping into a timer instead of immediately scheduling more output.

I think what I want is to change the loop to:

1. (same) when we're stalled on data input, we wait for an event from the source XHR
2. (same) when we're stalled on codec output, we wait for an event from the worker
3. (same) if we still have data to process, we just keep looping through via a scary-ass tail call
4. *on every requestAnimationFrame checkin*, after drawing (if necessary), send ourselves a postMessage or setImmediate to check in to the processing loop.
5. *on every audioprocessing event*, after buffering output, send ourselves a postMessage or setImmediate to check in to the processing loop.
6. for Flash audio, either fire a timer (blech) or use a callback from the Flash side to emulate the audioprocessing checkin

This should eliminate setTimeout from the timing paths for both audio- and video-bearing files. Posting a message to the window is a technique I've seen for scheduling something in the next run of the event loop when node's nextTick or IE/Edge's setImmediate isn't available, and should avoid the timer throttling for background tabs.

**Comment by brion** [comment]
(note: want to schedule processing on a separate event to avoid stuffing up critical timing paths for audio & display rendering)

**Comment by brion** [comment]
Bumping this up as it keeps annoying me and I already did the audio-feeder infrastructure.
