### ISSUE TITLE
Theora/Vorbis decoder failed mysteriously?

### ISSUE THREAD

**Issue by cromdev** [brion/ogv.js#321]
After encoding mp4 video to ogv (either with linux ffmpeg or windows XMedia Recode) it gives following output in console:
Vorbis decoder failed mysteriously? -135
Theora decoder failed mysteriously? -24

Tried with both vorbis (c-bunny video) and opus (c1-bunny video) audio codecs.

You can see it temporarily here: http://pbb2.linuxpl.info/video-flip-player/min2.html

Seems to be related to https://github.com/brion/ogv.js/issues/196

**Comment by cromdev** [comment]
also before looking at fix - if you could let me know how you specifically encoded curiosity.ogv file that would be great temporary solution for me

**Comment by brion** [comment]
It looks like your file doesn't have a skeleton track, so these are actually from re-seeking to the beginning of the stream after seeking to the end to calculate the file's duration manually (by checking the timestamps on the last packets in the stream).

When we get back to the beginning, we start with the header packets and the decoder complains they're not valid. This is a bug in the decoder insofar as we should silently skip over them. :)

You can avoid the seek-related warning (and avoid an extra network round-trip) by including a v4 ogg skeleton track in the file, which provides duration and seek metadata for the player to use. Unfortunately ffmpeg doesn't (currently) produce a skeleton track, but you can use ffmpeg2theora.

Player-side fix will probably be to check for header-ness of packets before tossing them in to the decoder after that seek.

**Comment by cromdev** [comment]
Thanks heaps, adding skeleton track (used ffmpeg2theora) made it.
Kudos for in-depth knowledge!

**Comment by sarang5** [comment]
Hi, I'm also facing the same issue.
Can you please brief your answer, brion?
