### ISSUE TITLE
Slow Video Decoding on Older iOS devices with latest 9.2

### ISSUE THREAD

**Issue by ghost** [brion/ogv.js#326]
Hi,

something interesting I've noticed, on an older iPad Mini (Model: A1432) running iOS 9.2 the video decoding is slow, with `Module._ogv_video_decoder_process_frame(buffer,len)` taking between 250ms and 1000ms to run at times. However it only happens at the beginning of playback (in the first 10sec). The lack of real debugging tool in Safari make investigating this real hard though.

The interesting bit is that I am entirely certain than running iOS9.1 (tested last summer) there was no such issue as I've benchmarked and run that player on the exact same device extensively. I've looked around to see if any changes had been made to Worker performance on Safari to no avail. I expect device to age but such a dip in performance is very weird to me.

Also the iPad in question is very barebones with the only other App installed being Google Chrome (not running either). 

Not sure if there is anything can be fixed here, thought I'd share this issue I've encountered.

**Comment by brion** [comment]
(closing out old issues)
