### ISSUE TITLE
vast support

### ISSUE THREAD

**Issue by notmani** [brion/ogv.js#327]
Hello,

Have you planned to support vast format in order to call tracking url, ... ?

**Comment by brion** [comment]
Is this https://en.wikipedia.org/wiki/Video_Ad_Serving_Template ? I'd recommend doing that at a higher level; the ogv.js API is largely the same as the native video/audio elements (and should align more with it in terms of event support when I have a chance to fix up some of the unimplemented bits) so a common layer should be able to use either and implement the parsing/tracking url handling.

**Comment by notmani** [comment]
Hello,
Yes, I'm talking about https://en.wikipedia.org/wiki/Video_Ad_Serving_Template / http://www.iab.com/guidelines/digital-video-ad-serving-template-vast-3-0/  . Ok you are right, there is some vast parser for <video> tag. I will try out.

**Comment by brion** [comment]
Great, let me know if it works or if it needs additional API support (there are some missing events that you might need for triggering tracking pings)
