### ISSUE TITLE
Auto-play video on Mobile Safari (without audio)

### ISSUE THREAD

**Issue by monofonik** [brion/ogv.js#332]
Wondering if anyone has attempted to implement auto-play support for Mobile Safari? 

Other inline video solutions work around the browser limitations by rolling the video without sound. The user can then click an unmute icon to enable audio (video continues to roll at current location). It's obviously not as simple as just muting the audio output - I expect the video stream must be handled entirely separately to the audio. 

We're keen to throw some resources at this in the coming weeks, and want to get any input / learnings from other contributors first.

**Comment by brion** [comment]
Roughly what it needs:
* detect failure to start up audio
* gracefully fall through from audio-based clock to the same timer-based clock used when playing video-only files

This probably requires switching some hard checks on hasAudio to check on which clock is being used; I'd been thinking of refactoring the time handling in general which should simplify this.

**Comment by brion** [comment]
And either disable processing of the audio channel, or (perhaps better) null-op the actual playback.

**Comment by sethurajan** [comment]
Hi @brion, Is there a way we can disable audio in the library through a setting so that we can achieve auto-play on both iOS and Android. We used to set demuxer.audioCodec to false inside loadAudioCodec function in previous ogv version as a quick-fix. But if we do that in latest ogv.js version, video itself does not load in Android. It works in iOS though.

**Comment by brion** [comment]
There's not a defined interface for that yet, no. Hacks not guaranteed to keep working.

**Comment by brion** [comment]
My recommendation is probably to stub out a code path in AudioFeeder to provide a null-op output that still maintains a playback timeline.

**Comment by brion** [comment]
Note I'm in the midst of a refactor of AudioFeeder as well, and have moved it out to https://github.com/brion/audio-feeder

**Comment by brion** [comment]
This now works if explicitly muted, which is good enough.
