### ISSUE TITLE
Cross-Domain Web Workers Errors

### ISSUE THREAD

**Issue by jtfell** [brion/ogv.js#333]
When hosting the 1.0 release on a static server, I get cross-domain errors when the web workers are initialised. I tried to resolve this issue by modifying the OGVLoader class to fetch the source (using httpXMLRequest) and generate a blob data url. This seems to work on some level, but there are a few outstanding issues with this approach:

1. The OGVLoader.base is unable to query the browser for the URLs of other files (eg. demuxers) when in a web-worker that has been invoked on a data url.
2. If this base variable is hard-coded (as a quick workaround), the audio plays but I have no video showing up. 

Is this the approach that you would expect to be the most effective to solve this issue? If it is, do you have any intuition on how to resolve these other issues. Or is there a better method to resolve this?

[Link to current progress](https://github.com/jtfell/ogv.js/commit/543e4fb9ab9c3c06c5b0a876d8d31374519241a2)

**Comment by brion** [comment]
Hmmm, tricky question. Web workers don't seem to like being loaded cross origin indeed!

Couple of possibilities offhand:
* prefetch all needed modules and push them all in together
* use an iframe proxy with an .html stub on the static origin

Will experiment and see which  ofthose seems to work best

**Comment by hartman** [comment]
If you properly setup CORS and use importScripts, like i did with https://github.com/ajaxorg/ace/pull/1761 for webworkers in the Ace editor, then it can work.

**Comment by brion** [comment]
@hartman so that's loading over XHR+CORS into a blob, making a URL with URL.createObjectURI(), and loading that into importScripts? funky :) Will give it a try.

**Comment by hartman** [comment]
funky it definitely is :)

**Comment by monofonik** [comment]
We've experimented with this approach ourselves - it works quite well. Here's the relevant commit on our fork - https://github.com/playground-xyz/ogv.js/commit/b6900adaa6fea45cc7a14ce56d66c8e938efce3f

Note we also had to hard code our default base URL in OGVLoader.js for this approach to work, but this could be handled instead by a build configuration or something.

**Comment by brion** [comment]
Can probably send the proper base URL in via postMessage in a pinch, I'll experiment.

**Comment by brion** [comment]
aac8cb3d0af1ebed5b862c518fb000a1a74f5d83 implements XHR->blob worker loading for cross-domain base URL, pre-concatenating the target class with the worker setup to avoid dealing with the extra importScripts inside the worker. Seems to work nice, I've merged it. :)
