### ISSUE TITLE
Add all media/video element properties

### ISSUE THREAD

**Issue by hartman** [brion/ogv.js#335]
Properties like autoplay, preload and controls are undefined. Even if write actions are not supported, read actions probably should be easy to support.

**Comment by hartman** [comment]
Just to get a bit better overview of what the interface looks like right now, I added
https://github.com/brion/ogv.js/wiki/MediaElement-interface-implementation-status

**Comment by brion** [comment]
Most of those should be very easy to stub out; a few look easy to implement and can be done quickly. I'll block out a schedule to catch up on this and other issues in the next few weeks (I've still got some travel this month so have to structure my time a little more carefully!)

**Comment by brion** [comment]
Think that was most of em? closing this one out; there's some separate issues now for the more important-sounding props/events to implement

**Comment by hartman** [comment]
preload is still missing.
