### ISSUE TITLE
Implement playbackRate

### ISSUE THREAD

**Issue by brion** [brion/ogv.js#352]

**Comment by velochy** [comment]
@brion a small heads up but I am currently working on this. 

My current plan is to integrate tempo changing apparatus into the audio-feeder project by building a lightweight API around a pure JS phase vocoder implementation (that I could port over from another project and release under MIT), as it seems like the least invasive method requiring the least changes in ogv.js or audio-feeder, moving most of the hard stuff into a separate package.

The phase vocoder in question is at https://github.com/velochy/phase-vocoder.js, and the intended changes for audio-feeder can be seen at https://github.com/velochy/audio-feeder/commit/cfc5467d69702114354ef0c4441a70789889ad5d

There is a fair bit of work to do to get the phase vocoder api to match up to the changes made, but I should be able to get most of it done over the coming week. 

Any thoughts and all comments would be very welcome.

**Comment by brion** [comment]
@velochy that's pretty awesome!

I think the OGVPlayer side mostly will need to work in input units (except maybe in keeping a target buffer duration in real time units?). As long as it can get current time and buffered-length in input units, I'm pretty sure it'll work fairly naturally. :D

Feel free to poke me for code review or comments/testing!

**Comment by brion** [comment]
Implemented by @velochy's patch. Woohoo!

**Comment by jseward311** [comment]
Will this work be included in docs and also available for preview at https://brionv.com/misc/ogv.js/demo/

**Comment by brion** [comment]
I'll add to the readme docs. You can see a current demo at https://brionv.com/misc/ogv.js/demo2/ until I finish the release and update the main demo. :)
