### ISSUE TITLE
Release a alpha version of 1.1.0 please

### ISSUE THREAD

**Issue by paladox** [brion/ogv.js#365]
This is so we can update ogv.js in timedmediahandler to this release.

**Comment by hartman** [comment]
Playground patch for ppl wanting to experiment:
https://gerrit.wikimedia.org/r/#/c/284016

**Comment by paladox** [comment]
Thanks.

Maybe we can ship both 1.0 and 1.1 but add a config to choose which one. Would allow us to test easier since if there are further updates you would need to rebased if they conflict (Unlikly but can happen.)

**Comment by brion** [comment]
There would be no reason to ship 1.0; 1.1 remains backwards-compatible.

**Comment by paladox** [comment]
Oh.

**Comment by brion** [comment]
done a8dbd0d -> https://www.npmjs.com/package/ogv

**Comment by paladox** [comment]
Thanks.
