### ISSUE TITLE
After playback ends paused property should be true

### ISSUE THREAD

**Issue by hartman** [brion/ogv.js#367]
To quote from: http://www.w3.org/TR/html5/embedded-content-0.html#playing-the-media-resource

> When the current playback position reaches the end of the media resource when the direction of playback is forwards, then the user agent must follow these steps:

> If the media element has a loop attribute specified and does not have a current media controller, then seek to the earliest possible position of the media resource and abort these steps.

> As defined above, the ended IDL attribute starts returning true once the event loop's current task ends.

> Queue a task to fire a simple event named timeupdate at the media element.

> Queue a task that, if the media element does not have a current media controller, and the media element has still ended playback, and the direction of playback is still forwards, and paused is false, changes paused to true and fires a simple event named pause at the media element. <---------

> Queue a task to fire a simple event named ended at the media element.

> If the media element has a current media controller, then report the controller state for the media element's current media controller.

**Comment by hartman** [comment]
Slightly related, I notice that after playback currentTime == 0, but it should not have been reset to 0 in that case. It should that after play() (if ended == true).

See part starting with:
> When the play() method on a media element is invoked, the user agent must run the following steps.

**Comment by brion** [comment]
Might be fixed on setsrc branch, untested as I am on a plane.
