### ISSUE TITLE
Seek after ended, then play starts video playback, but not audio playback

### ISSUE THREAD

**Issue by hartman** [brion/ogv.js#370]
Play a video till the end. You encounter #367. Now instead of playing from scratch using .play(), we will seek to a place in the middle. Now try playing. The video starts, but the audio does not.

Possible overlap with #346 ?

**Comment by brion** [comment]
Yeah, sounds like confusion of the pause/play states... I think the audioFeeder gets closed out at end and may not be getting started up again.

_looks_

Oh god, it's awful in there. :) Yeah, I need to redo the handling of the end-stage state so it can recover and keep being used.
