### ISSUE TITLE
Exception during playback

### ISSUE THREAD

**Issue by hartman** [brion/ogv.js#393]
I was debugging some javascript and starting playback of a movie (using the 1.1.0 alpha version in gerrit) and ran into this exception

NotFoundError: DOM Exception 8: An attempt was made to reference a Node in a context where it does not exist.

removeChild
doProcessPlay
finish
process
doProcessing

```
								// Ready to draw the decoded frame...
								if (thumbnail) {
									self.removeChild(thumbnail);
									thumbnail = null;
								}
```

**Comment by brion** [comment]
looks like if something gets triggered after the poster property is set, but before the image loads, this'll happen as it hasn't been added to the dom yet. I can fix that easy.
