### ISSUE TITLE
Muted videos should be able to autoplay on IOS

### ISSUE THREAD

**Issue by omegdadi** [brion/ogv.js#397]
Videos can't be autoplayed in IOS due to audio autoplay limitations, however if the player is started muted, the video could still play using requestAnimationFrame to drive the frame playback.

To accomplish unmuting on user interaction, you could then seek the audio to the current time of the video, play it, and switch to use the audio time to drive the video.

This is an incredibly common use case, so hopefully this makes it in!

**Comment by hartman** [comment]
To me that sounds more like it would belong into a plugin for a videoplayer framework like video.js, not in this particular library.

**Comment by brion** [comment]
merging into https://github.com/brion/ogv.js/issues/112
