### ISSUE TITLE
WebSockets? Live Streaming?

### ISSUE THREAD

**Issue by sassyn** [brion/ogv.js#399]
Hi,

Can we do a live streaming via NodeJS using WebSockets?
I know about JSMPEG - and wonder if this project support this as well?

Thank You

**Comment by brion** [comment]
Current plan is to [add an analogue of the Media Source Extensions interfaces](https://github.com/brion/ogv.js/issues/359), which will allow for demuxing straight from buffers obtained separately, whether loaded via XHR or Web Sockets.
