### ISSUE TITLE
Create the ogv.js files for 1.1.2-alpha.3 release

### ISSUE THREAD

**Issue by paladox** [brion/ogv.js#401]
Hi could we create the files for 1.1.2-alpha.3 release like we did for 1.1.2-alpha.0 or can we do it in the next release 1.1.2-alpha.4 please to test in TimedMediaHandler.

**Comment by brion** [comment]
Still fixing a couple bugs but I think it's close. :)

**Comment by paladox** [comment]
Thanks :)

**Comment by brion** [comment]
alpha4 now on npm & here: https://github.com/brion/ogv.js/releases/tag/1.1.2-alpha.4

**Comment by paladox** [comment]
Thankyou very much and thanks for working on ogv.js :).
