### ISSUE TITLE
question

### ISSUE THREAD

**Issue by publicocean0** [brion/ogv.js#417]
hi , i m working for developping a new player audio/video. 
My player dont receive a file but a generic inputstream  using stream class. 
Now it receive a mp4 stream on the fly , segmenting it i can append buffers using Multimedia extensions in video component. 
I was answering if it is possible to do it also with ogg format  and if you have a javascript class making it in your project. I m available to share my code.

**Comment by brion** [comment]
Closing out old questions from issues. Related issue: https://github.com/brion/ogv.js/issues/359 (Media Source Extensions implementation)
