### ISSUE TITLE
error configuring liboggz build on Windows Subsystem for Linux

### ISSUE THREAD

**Issue by brion** [brion/ogv.js#422]
Autotools stuff is too scary to try on raw Windows, but the Windows Subsystem for Linux ought to provide suitable Ubuntu userland.

On final Windows 10 1607, WSL freshly installed, updated, and set up various base packages. emsdk built locally, sdk-master-64bit. Did 'npm install', then make clean and various makes. Manually added 'node' symlink in /usr/local/bin to override the default PATH emsdk node dir that confused it. Installed autoconf/automake, then libtool, then pkg-config, then also tried libogg-dev just in case. Still getting a fail here:

```
checking for getopt_long... yes
../../../liboggz/configure: line 12731: syntax error near unexpected token `OGG,'
../../../liboggz/configure: line 12731: `  PKG_CHECK_MODULES(OGG, ogg >= 1.0, HAVE_OGG=yes, HAVE_OGG=no)'
ERROR:root:Configure step failed with non-zero return code 2! Command line: ['../../../liboggz/configure', '--prefix=/mn
t/c/Users/brion/src/media/ogv.js/build/js/root', '--disable-write'] at /mnt/c/Users/brion/src/media/ogv.js/build/js/libo
ggz
make[1]: Entering directory `/mnt/c/Users/brion/src/media/ogv.js/build/js/liboggz'
make[1]: *** No targets specified and no makefile found.  Stop.
```

**Comment by paladox** [comment]
Could this be a bug in the windows Linux? I'm using windows Linux too and I am on the windows insider and that seems to have got plenty of fixes.

**Comment by brion** [comment]
Works in Win10 Creators Update (1703) with a fresh Ubuntu 16.04 setup.
