### ISSUE TITLE
Optimize libvpx VP8 decoding hotspots for emscripten

### ISSUE THREAD

**Issue by brion** [brion/ogv.js#429]
Hot spots in the VP8 decoding:
- sixtap filter for motion prediction, especially the 16x16 and 8x8 variants
- loop filter

The loop filter C (non-inline-assembly) code is sliiiiightly faster if I avoid the signed char conversion (since we have no handy SIMD for signed chars); experimental bits in 'emscripten' branch on my libvpx work fork -- https://github.com/brion/libvpx

I don't see an obvious way to improve the sixtap filter without SIMD; it's a bunch of integer multiplication and addition and the constant scales are mostly already factored out by LLVM.

**Comment by brianxautumn** [comment]
Rewrite to javascript, then detect if SIMD or offscreen canvas are available. Firefox already has offscreen canvas, Firefox and Edge both have SIMD in the dev branches. Chrome will probably add offscreen canvas too.

Worse case scenario, serial operation with less memory impact, best case, true parallel operations.

**Comment by brion** [comment]
Long term I'd *love* to be able to parallelize and make use of multiple CPU cores for the decoder! (Even phones usually have 2 cores these days.) I just don't have the time to rewrite it yet... :)

@brianxautumn if you're interested in diving into a parallelizable pure-JS VP8 or VP9 decoder (or pure-JS plus WebGL for GPU bits), I have some old notes at https://brionv.com/log/2016/05/19/peeking-into-vp8-video-decoding-performance/ and https://brionv.com/log/2016/05/20/vp8-parallelization-continued/

Some of those musings will be dead ends, but overall it looks like a few threads of parallelization on CPU are doable, as long as blocks are handled in the right order and the threading communication overhead isn't too high.

A few quick notes on compatibility:
* Firefox and Chrome tend to pick features up the fastest, but since they have native Ogg and WebM support they're not my key performance targets.
* Safari is a key target for playback compatibility. No sign yet of SIMD or SharedArrayBuffer.
* Edge has SIMD, but not yet SharedArrayBuffer.
* IE 10/11 are still a target for ogv.js but we can flip back to the emscripten decoder just for it if it's necessary to use techniques that won't work or run too slow on it! (It has a cruddier JIT and no new JS features.)

In the shorter term, I'm looking mostly at seeing if SIMD can be used in the libvpx hotspots for Edge, and any low-level tweaks that can be done to improve things on Safari until Apple decides to accept SIMD in JavaScriptCore.

**Comment by brianxautumn** [comment]
I just tried the curiosity video on ios chrome, firefox, and safari and neither would play it. All latest versions. 

Not to mention, even if it does play the video format, it would be only video player that can support its own UI and play embedded videos without using pop out mobile player. 

I can start with a straight js rewrite, which might take a while, then figure out which direction it should go it, it would be easier to modularize the components once they are in javascript.

**Comment by brion** [comment]
Is this with the JS demuxer? Might not have the necessary ES6 support deployed yet in Safari...

(Note that Chrome and Firefox on iOS use the same underlying web & JS engine as Safari, so they should all work or not work equally. The nestegg & libvpx pairing works on both iOS 9 and 10 but decoding performance isn't where I want it.)

**Comment by brianxautumn** [comment]
Nope, I mean native. The plain old webm file with no player won't work. I just tried on 2 different iPhones and it won't play. They prompt me to download it and play with another app. Ogv works even with the es6 demuxer, even without using babel to compile to es5.

**Comment by brion** [comment]
Ah yes, indeed there's no native WebM on iOS web browsers, even in Chrome and Firefox. Great that the ES6 is working. :D

(The VLC app will play back WebM files on device if you want to compare against 'best case' native-code performance, but it has no web integration other than being able to launch it after downloading a file.)

**Comment by brianxautumn** [comment]
That's what I'm saying. Playing webm is a total usability headache for mobile users that just want to play a video directly in the page.

**Comment by brianxautumn** [comment]
But I guess that does mean researching what works best on mobile platforms.

**Comment by brianxautumn** [comment]
Hey did some googling:

> Long term I'd love to be able to parallelize and make use of multiple CPU cores for the decoder! 

This is also going to take moving the video decoder to the main thread. Most browsers don't have thread to thread communication, however most can do network requests from worker threads, so perhaps it is worth looking into putting the networking and demuxing on its own thread and moving video decoding to the main thread, and possibly have to do one extra transfer to get the audio packets to their own thread. Like you said in your blog, it will be difficult to tell what the speedup will be.

With rebuilding the js decoder from the bottom up, it can be possible to measure the linear time vs different parallel improvements in a separate test harness, and then make a more educated decision as to which path to take.

**Comment by brion** [comment]
I did some hotspot improvements in the loop filter a while ago which shaved a few percent off VP8 decode time (mostly by avoiding unnecessary int<->char conversions), so closing this out.
