### ISSUE TITLE
Make core build work on Windows (split out emscripten modules)

### ISSUE THREAD

**Issue by paladox** [brion/ogv.js#437]
Hi could you add support for building this in windows please?

Make command is not available in windows.

We could use npm and use the packages there to build this please?

**Comment by brion** [comment]
My plan is to separate out the decoder and demuxer modules to their own npm modules, which can then be fetched precompiled when you're just dealing with the player core. That should make it much easier to convert the rest of the Makefile over to grunt tasks.

**Comment by brianxautumn** [comment]
I'll start migrating the new demuxer to its own npm module this week

**Comment by paladox** [comment]
Oh thankyou.

**Comment by brion** [comment]
@brianxautumn let me know what you think of this updated internal API for the demuxer (just made a bunch of updates to the page); I'll be converting the emscripten modules over in the next few days:

* [OGVDemuxer](https://github.com/brion/ogv.js/wiki/Proposed-module-interfaces#ogvdemuxer)
* [OGVInputStream](https://github.com/brion/ogv.js/wiki/Proposed-module-interfaces#ogvinputstream)

In addition to switching from a web of callbacks to cleaner promises, I'm inverting the control between the network input stream and the demuxer. This'll allow your JS WebM demuxer to manage its seeking more cleanly, and should let you do things like finishing loading cues if two seeks are issued very quickly in sequence.

**Comment by brianxautumn** [comment]
+1 for the promises. The api does look cleaner, I still think there should be a scrub vs seek method, but it's up to you!

 I'll wait on those until you update the emscripten modules for adding promises.

Todo list: 

- Pull out js demuxer to its own repo

- Add dropdown option to switch between demuxers on demo

- Start Update OGVWrapperCodec to ES6, will make it so you don't need that `demuxer.seek` hack

**Comment by brion** [comment]
While modular cleanup is good, I'm not gonna bother with Windows build -- WSL works these days ;)
