### ISSUE TITLE
External reference to library

### ISSUE THREAD

**Issue by ron666** [brion/ogv.js#445]
Is there a place I can call the library external, via CDN or a public URL?

**Comment by brion** [comment]
Currently no, you'll need to copy the library to your own deployment location. (If not using npm, fetch the latest .zip from the releases tab https://github.com/brion/ogv.js/releases to make sure you get the pre-compiled ready to use files.)

**Comment by ron666** [comment]
Thanks. Hope you have plans to put it in a CDN it would be very helpful to use it in the project I'm working on
