### ISSUE TITLE
Support 4:4:4 chroma subsampling for VP9

### ISSUE THREAD

**Issue by AdmiralPotato** [brion/ogv.js#471]
I'm excited about the new support for VP9 as of V 1.4.0, though I am aware of the current limitation of supporting only the 4:2:0 chroma subsampling format. Some of the content that I am creating is particularly sensitive to this type of quality loss, so I am very interested in seeing support for 4:4:4.

Knowing that it probably wouldn't work correctly, I thought that it would be an interesting experiment to see what happens in the case of loading in a 4:4:4 video. Not entirely surprisingly, while the `y` channel survived decoding intact, the `u` & `v` channels seem to be pixel doubled out past the scale of the canvas - but seem to be otherwise looking intact.

I have attached a test file and the output that was generated from the 1.4.1 release to illustrate the interesting transformation.

[hella_hearts_d-48-960x540-yuv444p-5000-webm.zip](https://github.com/brion/ogv.js/files/953438/hella_hearts_d-48-960x540-yuv444p-5000-webm.zip)

Desired:
![hella_hearts_d-48-960x540-source-frame_0](https://cloud.githubusercontent.com/assets/820844/25362511/8781f650-2911-11e7-931b-fe36d7adaca6.png)

Actual:
![hella_hearts_d-48-960x540-yuv444p-5000-webm-frame_0](https://cloud.githubusercontent.com/assets/820844/25361858/bd259f4a-290d-11e7-91b6-1bb99f98f82b.png)

**Comment by brion** [comment]
Thanks, sample files are always helpful! I'm _pretty_ sure this will be easy to fix once I get in there and poke it. :)

**Comment by AdmiralPotato** [comment]
I had my friend @SolraBizna look into this, and he was able to create a solution for what I needed in my use case - this was the patch that he came up with. It seemed to be somewhat trivial, just outside of my comprehension on the topic.

```diff --git a/src/c/ogv-decoder-video-vpx.c b/src/c/ogv-decoder-video-vpx.c
index f859acd..370c299 100644
--- a/src/c/ogv-decoder-video-vpx.c
+++ b/src/c/ogv-decoder-video-vpx.c
@@ -124,11 +124,24 @@ static int process_frame_return() {
 			continue;
 		}
 		foundImage = 1;
-		ogvjs_callback_frame(image->planes[0], image->stride[0],
-							 image->planes[1], image->stride[1],
-							 image->planes[2], image->stride[2],
-							 image->w, image->d_h,
-							 image->w >> 1, image->d_h >> 1); // @todo pixel format
+		switch(image->fmt) {
+		case VPX_IMG_FMT_I444:
+			ogvjs_callback_frame(image->planes[0], image->stride[0],
+					     image->planes[1], image->stride[1],
+					     image->planes[2], image->stride[2],
+					     image->w, image->d_h,
+					     image->w, image->d_h);
+			break;
+		default:
+			// @fixme how to handle this?
+			printf("warning: unknown pixel format 0x%04X, decoding as YUV420\n", image->fmt);
+		case VPX_IMG_FMT_I420:
+			ogvjs_callback_frame(image->planes[0], image->stride[0],
+					     image->planes[1], image->stride[1],
+					     image->planes[2], image->stride[2],
+					     image->w, image->d_h,
+					     image->w >> 1, image->d_h >> 1);
+		}
 	}
 	return foundImage;
 }
```

**Comment by SolraBizna** [comment]
I would've made a PR, but I wouldn't want that "unknown pixel format" printf to suddenly start getting called in production code, and I didn't have the time to look into handling this the right way. (Also, if I were taking ownership of this problem I'd really want to also add and test 4:2:2 support, and I should be getting back to work already... >_>;)

**Comment by brion** [comment]
Looks about right, can handle 4:2:2 similarly. I'll see if I can whip up a point release.

**Comment by brion** [comment]
Enjoy -- 1.4.2 patch release should be out now with the fix including 4:2:2 and 4:4:4.

Beware another problem I noticed though -- due to an old hack in initialization, it may fail on WebM files shorter than 256kb. That should be gone in 1.5.x, I'll be making some bigger refactorings to the i/o and demuxer path.

**Comment by AdmiralPotato** [comment]
!!!!!!!!!
😄 That was so fast!!! Thank you so much! 😄
