### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by publicocean0** [brion/ogv.js#475]
Some observations on your initial iphothesis

1) you use ajax for progressive download, but in general it is possible to download also from other datasource type. So it would be necessary to realize a prototype ..... generic stream.
2) all streams can be handled in async way (also synchronous stream), but the opposite affermation is not true. So the stream might use promise api.
3) The player is a object, the mediasource is another, and the demuxer is another: You have to consider mse use a specific way to read the stream and some case must be changed for it. 

Reorganizing a bit the code you could make a solution for all browser and also for streaming. Anyway it is already a super big work

**Comment by brion** [comment]
All good suggestions! I'm folding this back into https://github.com/brion/ogv.js/issues/359 to consolidate and will add notes there.
