### ISSUE TITLE
split project in modules

### ISSUE THREAD

**Issue by publicocean0** [brion/ogv.js#478]
For opensource reason and reusability , it would be cool to split the project in modules:
- player 
- demuxer
- decoder

Consider who use MSE already has a demuxer for reading chunks ... so if you realize modules it is easier do integrate in the project . In addition MSE dont contains demuxer. It receives chunks already well formed.

**Comment by brion** [comment]
(merging this to https://github.com/brion/ogv.js/issues/374 )
