### ISSUE TITLE
WebM files under 256kb fail to initialize

### ISSUE THREAD

**Issue by brion** [brion/ogv.js#487]
This predominantly affects audio-only WebM files, which are smaller than video files generally.

Currently, the i/o wrapper for the nestegg demuxer waits until 256kb have been read before running nestegg_init() as it's not very recoverable if it fails -- as a result, when the higher-level player code reaches end of file and hasn't seen any metadata come back, everything falls over.

Need to either signal the eof condition to the demuxer module, or have the demuxer retry nestegg_init on initial input until it works, and figure out how to recover when it fails early.

**Comment by jseward311** [comment]
Thank you for your efforts on this bug!

**Comment by jseward311** [comment]
This may have borked seek functionsality. 

Setting player.currentTime = 1.0;
player.play();

Breaks playback for me.
