### ISSUE TITLE
[audio/webm] player.currentTime = Anything other than zero breaks seek.

### ISSUE THREAD

**Issue by jseward311** [brion/ogv.js#489]
https://github.com/brion/ogv.js/issues/487
This may have borked seek functionality.

player.currentTime = 0;
player.play();
setTimeout(function(){ player.currentTime = 3.0; }, 2000);

Breaks playback seek.

**Comment by brion** [comment]
Is this on the audio webm files only, or on all files? Note that currently, seeking in webm files requires index cues in the file, which may not always be present on audio files. I'll have to double-check...

**Comment by jseward311** [comment]
Correct this is on audio only webm files.

On Jan 22, 2018 6:19 PM, "Brion Vibber" <notifications@github.com> wrote:

Is this on the audio webm files only, or on all files? Note that currently,
seeking in webm files requires index cues in the file, which may not always
be present on audio files. I'll have to double-check...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/brion/ogv.js/issues/489#issuecomment-359607640>, or mute
the thread

**Comment by jseward311** [comment]
Thanks again, 

We will try to find a workaround for this. Maybe the brute force solution you are talking about. 

Have not found a method to add cues to audio/webm as of yet.

**Comment by jseward311** [comment]
Awesome. We can test this on small and larger files. In our case, small files of ten minutes or less are the norm but they can run up to an hours or so.

**Comment by brion** [comment]
Great, if the file's in memory, then it should work reasonably well even for longer files.

**Comment by jseward311** [comment]
After implementing this fix I have found that seeking is wonky. Seeking backwards tends to play from the beginning of the file. Seek and playback work which is great. Seeking seems to not find the correct location at times though.

**Comment by brion** [comment]
If you have a reproducible test case let me know; I'll keep an eye out in case can repro on my end.

**Comment by jseward311** [comment]
[ogv-test.zip](https://github.com/brion/ogv.js/files/1674324/ogv-test.zip)

Sent this as an email but was not sure it would make it through.

The above zip contains a webm/audio only file and the player with a seek bar. 
You will notice the seek actually goes to the beginning of the file. Also some other randomness. 

Thanks again, 
Josh

**Comment by brion** [comment]
@jseward311 yeah I can confirm something's still janky there. Reopening, I'll take a more detailed look. Most likely something's failing to update state somewhere, so it thinks the demuxer is at the target time when it's still at 0.

**Comment by brion** [comment]
So I think this is because we don't have the right cluster offset? Nestegg is returning packets after the seek but with the wrong timestamp, I think because it caches the base timestamp at cluster boundaries and it's not getting reset properly.

When seeking to later times, the wrong timestamps from the beginning get reset at a cluster boundary, but when seeking to earlier times we think we're already at the target time, and packets begin playing from the beginning of the file as if they were the middle.

Need to find the exact right offset to pick up from, or else reinitialize the whole stream from the beginning.

**Comment by brion** [comment]
Ok, this seems to fix it. Releasing soon along with other recent perf fixes in 1.5.7...
