### ISSUE TITLE
OGV Seek issues when reaching end of WebM.

### ISSUE THREAD

**Issue by thedracle** [brion/ogv.js#495]
If we play the following clip to completion in OGV.js, and then attempt to seek, it ends up in a permanently locked state, and never recovers or plays back again:

https://s3-us-west-1.amazonaws.com/hirevue-temp/ogv-demo.webm

As far as I can tell, it ends up in 'doProcessLinearSeeking', and codec.frameReady is always false.

It ends up evaluating:
OGVPlayer.js @745: 
```
 log('stream ended during linear seeking on video');
dataEnded = true;
continueSeekedPlayback();
```

And inside that, both codec.frameTimestamp and codec.audioTimestamp are -1.

As far as I can tell, if the stream has ended, and the codec timestamps are now in a broken state, it never will end up recovering to seek to the position in the track I'm trying to seek to.

Any help, or suggestions on a workaround here, would be greatly appreciated.

**Comment by brion** [comment]
Can confirm, will see if I can figure it out...

**Comment by brion** [comment]
Hmm, this is suspicious:

```
ogv.js:66:7664
[8653ms] i/o error: Error: seek past end of file
```

It's seeking to position 1660385; the file is 1660474 bytes so this ... should work. Looking further, the underlying StreamFile object thinks the file length is 1048576 bytes. This may be a CORS header problem?


```
Content-Length | 1048576
Content-Range | bytes 0-1048575/1660474
```

Content-Range has the correct total length, but there's no Access-Control-Allow-Headers to allow access to Content-Range, so it may be falling back to the Content-Length header (normally used when not doing partial requests).

If I copy the file to my local web server and load it into the demo it seems to seek back to start ok both before and after completion.

It should handle this case more gracefully than it does, though without CORS to allow use of Range header and its response data, seeking is tricky (though could be done in cached areas).

**Comment by thedracle** [comment]
I can modify the Access-Control-Allow-Headers if that would help, where did your research take you?

**Comment by brion** [comment]
I finally figured this one out -- the webm demuxer stops reading packets at the beginning of the cue points. When we ask to seek back to 0, we first flush the demuxer's buffers and then ask it to seek to the beginning with the cue points... it believed that it was already at this position and didn't issue a seek, so things weren't in proper order to fetch more data.

Fix is to reset the BufferQueue's position on flush, so the seek correctly is issued. Will commit shortly.
