### ISSUE TITLE
Third order Ambisonics support demands 16 Audio channels, can it be done without splitting in to 8 channel files for loading from files?

### ISSUE THREAD

**Issue by bossesand** [brion/ogv.js#502]
This is a question, as Documentation of your Audio implementation is not so easy to find.
I have a project OHTI for Headtracked Ambisonic audio using Omnitone. [https://github.com/bossesand/OHTI](url)
I have found that to load local files with more than 8 channels they need to be split in to channel 1-8 and 9-16 to load.

Do ogv support WebM Opus Audio only files with 4 to 16 channels?
The current limitation in WebAudio is 8 channels as max, and as I understand it you do not use WabAudio do you have this limitation?

**Comment by bossesand** [comment]
As I understand it from tests using omnitone it is possible to load and play Wav, Opus and ogg files can be loaded as single multichannel files, I have tested with up to 16 channels.

Do ogv have support for rotating ambisonic sound in binaural playback?

**Comment by brion** [comment]
It should decode all channels in the file, but I'm not sure what'll happen to it going out over WebAudio. :)

Note there may be some arbitrary limits in the audio-feeder module that intermediates the output path -- in particular there may still be a hack to limit output to 2 channels: https://github.com/brion/audio-feeder/issues/17
