### ISSUE TITLE
IE11 have a issues,   Report this mistake “No supported backend ”

### ISSUE THREAD

**Issue by hubo123** [brion/ogv.js#503]
IE11 have a issues,   Report this mistake “No supported backend ”

**Comment by brion** [comment]
IE 11 requires Flash for audio output; is Flash installed and enabled?

**Comment by brion** [comment]
The "slow demux" line? That's a harmless debugging message in an old version of ogv.js.

**Comment by brion** [comment]
Closing out; please reopen if still having problems with current release.
