### ISSUE TITLE
I'd like to just grab a frame at a specific time frame

### ISSUE THREAD

**Issue by davidgatti** [brion/ogv.js#508]
Hello good people :) 

I did do some searches in the Issue section and wasn't able to find what I was looking for, thus me taking the liberty to open an Issue. 

I have this situation where I use Kinesis Video Stream to stream live data, and do facial recognition. When A face is found I then query KVS to grab a fragment of the video stream where the face was detected. 

In return I get a 2sec .webm file, from which I'd like to get a still frame, at the correct time stamp. I could do this with ffmpge - but I rather not do it if there is a native JS library that can handle decoding of .webm.

From the repo I don't see there being a `grabFrame()` function. So my question is this: 

- did I miss something, and if not, how could I do it? 
- is there maybe a different library that you can recommend that dose what I need in native JS? Just do the decoding, and spit out a frame instead of a live feed?

Any help would be gravelly appreciated.

**Comment by brion** [comment]
For a server-side app I'd probably recommend shelling out to ffmpeg -- it's efficient, well supported, and easily produces various formats, giving you either raw YUV data or RGB conversions.

For a client-side web app (which is ogv.js's primary target) you could use it just like a native `<video>` element to load a file, seek to a position by setting the `currentTime` property, and on completion snapshot copy the RGB canvas output by reaching into the `<ogvjs>` element to find its own `<canvas>` as a data source for `drawImage()`. Getting the raw YUV data would require slightly modifying `OGVPlayer` to expose the frame data before painting to the canvas, but would work.

If you really want you could load the low-level decoder and demuxer classes in a Node server environment and dig out the raw YUV data, but I wouldn't recommend it. They're not stable APIs and not really convenient to use, and decoding will be slower than the well-optimized native code in ffmpeg.

**Comment by davidgatti** [comment]
Got it, thank you.

**Comment by brion** [comment]
Closing out issue. :)
