### ISSUE TITLE
A/V Sync issues when playing clip with variable frame rate and 48khz OPUS

### ISSUE THREAD

**Issue by thedracle** [brion/ogv.js#509]
I am recording WebM with VP8/OPUS, and then playing it back with OGV.js.

When I was recording 44100Hz VP8/VORBIS, things appeared to maintain sync while playing for the duration of several minutes.

Now I am resampling to 48000Hz for VP8/OPUS, and the playback quickly falls out of sync within the duration of a minute.

If I seek to the position in the track where the clip became out of sync after a minute of continuous playback, it will be in sync, and if I play it back in any other player (Chrome, FFPLAY) it is in sync throughout the duration of the clip.

There are two unusual things about these clips. First the frame rate is variable, and can fluctuate ~22-30FPS.

Second, the audio no longer fits evenly into distinct sized chunks, so the audio no longer has uniform sized frames, and the difference in PTS from frame to frame differs sometimes.

The Clip can be found here, and I fixed the CORS issue on that bucket regarding pulling Content-Range, and reproduced the issue by jury rigging the player here (https://brionv.com/misc/ogv.js/demo/) to point at my clip.

https://s3-us-west-1.amazonaws.com/hirevue-temp/syncbug.webm

Hitting the same URL in raw Chrome everything is synced (I know there is a little static issue to do with the resampler.)

Since I control the encode source, any advice on what I can do to avoid this would be great.

Would it be helpful to encode the audio in smaller chunks? To try to set the video to hit a solid frame rate of 30FPS?

Would regular PTSes on the audio track be better? At fixed intervals?

**Comment by brion** [comment]
I'll have to test this, it's entirely possible there's a huge regression in 48kHz that I've failed to adequately test. (Most original sync testing was done with 44.1kHz output) Iirc the audio timing is based on the actual samples output, and the pts on audio packets isn't paid that much attention to... in which case translation from samples to seconds as a double might have rounding errors. And if it's resampling if webaudio is doing 44.1kHz that might complicate further as there could be rounding problems at sample boundaries.

**Comment by brion** [comment]
Packet boundaries, rather.

**Comment by thedracle** [comment]
I have some pretty good evidence it's probably to do with the differing PTS due to resampling in my 48khz clip. I remuxed the audio track with FFMPEG copying the video and audio codecs, and with the regular PTS, it plays back synced in OGV.js.

**Comment by thedracle** [comment]
Okay--- so it is *definitely* due to having variable sized audio packets and variable PTS timestamps.

I altered my encoder to only produce audio packets of the same size, and the same PTS delta, and I no longer see issues with AV sync with OGV.js

**Comment by brion** [comment]
Great -- still worrying though so I'll see if I can improve the resampler to handle small/variable packets better.

**Comment by brion** [comment]
I've improved the resampler in audio-feeder to compensate for the rounded-off fractional samples, which should make it to the ogv.js 1.6.0 release this week. Will double-check this is working correctly before the release. :)

Also I'll check if Safari supports setting the sample rate in AudioContext creation, which could eliminate the need to resample to 44.1 kHz except on IE/Flash playback.

**Comment by brion** [comment]
Couple of notes:
* Safari does *not* support setting the sample rate, so we're stuck with 44.1 kHZ output :)
* the resampling updates in audio-feeder don't help here (and in fact may make no difference based on the packet sizes I see)
* the sync bug sample file seems to implement variable-duration packets in a way ogv.js doesn't handle well, which is to use fixed-duration packets but declare that you should skip parts of them, then have overlapping PTS with the next packet.

I'm not 100% sure how it's stored in a way I can get at it yet, but in `ffprobe -show_packets` output this shows up with skip markers like this:
```
[SIDE_DATA]
side_data_type=Skip Samples
skip_samples=0
discard_padding=407
skip_reason=0
discard_reason=0
[/SIDE_DATA]
```

Currently ogv.js+audio-feeder handles the audio clock in terms of samples output, and it expects that audio packets will all line up perfectly. With the variable-duration packet sample, I end up playing the samples that should be skipped and then pasting the next packet on afterwards, which leads to audio running "slow" and video frames playing earlier than the audio it syncs to.

Correct fix is probably something like:
* figure out how to get that skip info and actually skip the samples
* also handle the case where there's extra padding or early end of audio not accounted for (cf https://github.com/brion/ogv.js/issues/239)

**Comment by brion** [comment]
Commit  `[22bfa58](/brion/ogv.js/commit/22bfa58a7c98c853c2a8a440d57a8e2bb41d8671)` resolves the original issue and gets the original variable-length Opus sample running in sync. :)

I'll leave other unexpected-PTS-related issues open on #239 and friends.
