### ISSUE TITLE
Inject a JS blob into the player instead of url?

### ISSUE THREAD

**Issue by jseward311** [brion/ogv.js#512]
Is there currently any way to send in a JS blob instead of a file path or url? 
Example:

private.player = player = new OGVPlayer({
            //debug: true,
            //debug: !!debugFilter,
            //debugFilter: debugFilter,
            wasm: false,
            memoryLimit: maxmem,
            enableWebM: true, // experimental, 
            **stream: private.videoStream**
        });

I have been modifying the OGVPlayer.js file pre-build to allow for this. But that file has been changing as of lately and does not ease the maintainability of this process. 

I understand there were other tickets on this subject but could not find the outcome or example. 

Thank again, 
Josh

**Comment by brion** [comment]
If you have an ArrayBuffer with the whole file to decode, you can turn that into a Blob and use URL.createObjectURL to create a usable URL for the blob. Slightly inefficient and it'll copy extra bytes around but it should work.

When refactoring is done I intend to have an MSE-like interface but this is a while down the pipe.

**Comment by jseward311** [comment]
Ah, yes I have been able to get the ObjectUrl. 
Unfortunately the object is filled with the arrayBuffer long after the player loads.

**Comment by brion** [comment]
@jseward311 I think the MSE-alike interface will be good for your use case if you're trying to do your own streaming over WebSockets and pipe buffers into the player. But this may not be done until summer or so, as I have to do more refactoring to supporting separate audio and video demuxers etc and have other server-side tasks to do before I can make use of it.

What you might want to do for now is replace the player's internal `stream` object (an instance from my `stream-file` package) with a custom one, which you can use to provide your own buffer reads out of the data you've read from the socket.

If that sounds like what you need, I think I can work a small API addition into the 1.6.0 update. (There's lots of internals refactoring and fixes from 1.5.x but in theory few external API changes.)

**Comment by jseward311** [comment]
This is exactly what has been done for prior releases. Unfortunately the ogvPlayer.js file has changed a good bit from the 1.5.7 version. I am trying to implement this in  master ogvPlayer.js file currently with mixed results.

**Comment by brion** [comment]
Perfect. :) Do you want to try making a patch & PR or shall I try to hack it in on my end and then make sure it works for you?

**Comment by jseward311** [comment]
I do not have a solid working patch as of yet. Not sure I will have one when you get time. I can post the could from the last version. This is the code we are "injecting" before build. 
1.5.7 extenal stream:

externalStream = null;

// get custom options to customize the player
externalStream = (typeof options.stream !== 'undefined') ? options.stream : null;

if (null === externalStream) {
                stream = new StreamFile({
                    url: self.src,
                    cacheSize: 16 * 1024 * 1024,
                });
            }
            else
                stream = externalStream;

This is the gist of it.

**Comment by brion** [comment]
Great, lemme try working that in on the updated master code...

**Comment by brion** [comment]
Try building master as of [cca6ed0](/brion/ogv.js/commit/cca6ed0d0d4aaac28f5a402801aef0a795dbd720) and see if that gets it working again for you.

**Comment by jseward311** [comment]
Verified stream is working!

**Comment by suman** [comment]
Hi Joshua,

Can you share the code that how exactly you achieved this ? 

I am trying to understand how you made  **custom stream** compatible with one from ogv.js.  Shall I need to create all the methods and properties of **Streamfile** class that needed by OGVplayer.js ?

If you can please share the code, that will be really helpful.

My original goal is: using ogv.js, play the the buffers that received by websocket or any other method.
