### ISSUE TITLE
Short Vorbis audio files not playing.

### ISSUE THREAD

**Issue by jseward311** [brion/ogv.js#513]
Recently changed the bitrate to 14 kb/s and noticed that short audio recordings are no longer playing in OGV.js. The reason for the change was file size. Files less than 17 seconds are not playing and stop immediately on load. These files do play in VLC and the browser. No debug errors. 

Webm files with audio and video continue to play no matter the length. 

Bitrate: 14 kb/s 
Sample Rate 8000 Hz
Bits per sample: 32
[bitrate.zip](https://github.com/brion/ogv.js/files/2856904/bitrate.zip)

**Comment by brion** [comment]
Hmm, the attached file plays ok for me in the current release and latest master. (I'm testing by dragging bitrate.webm from file manager onto the demo page https://brionv.com/misc/ogv.js/demo/ then hitting 'play'.)

Might be something funky about the HTTP loading with small files though, I'll try testing that way in a bit.

**Comment by jseward311** [comment]
I am still working on an upgrade path to latest and greatest. Still working with 1.5.7 
The ideal situation is build 1.5.8 or master with custom code injected to load the files from a websocket or blob for that matter. Will get there eventually. 

In the mean time I will pull down the release version 1.5.8 and test static files with that.

**Comment by brion** [comment]
Great, let me know if that resolves it or not; I don't see anything obvious in 1.5.8 or 1.6.0-prerelease that should have altered this specific behavior, so it might be an edge case with how the files are loaded & played that's not catching in my testing yet.

**Comment by jseward311** [comment]
Built 1.6.0 works with stream! 

Still no luck on short files :-(

Seeks to beginning of file and stops. 

Console logs with debug set to true:
[116.8ms] got input 21081
ogv.js:18 [117.8ms] stream is at end!
ogv.js:18 [244.2ms] fireEventAsync loadedmetadata
ogv.js:18 [244.7ms] fireEventAsync durationchange
ogv.js:18 [245.2ms] fireEvent loadedmetadata
playerViewModel.js:33 player.currentTime = 0currentTime=0.01
ogv.js:18 [263.4ms] requested seek to 0.01, mode exact
ogv.js:18 [264.1ms] pausing at 0
ogv.js:18 [264.9ms] canceling old processing timer
ogv.js:18 [280.9ms] fireEvent durationchange
ogv.js:18 [289ms] canceling old processing timer
ogv.js:18 [290.3ms] pausing at 3.8638999999966472
ogv.js:18 [297.9ms] fireEventAsync seeking
ogv.js:18 [303.3ms] got input 19004
ogv.js:18 [304ms] stream is at end!
ogv.js:18 [304.8ms] stream ended during linear seeking on audio
ogv.js:18 [305.4ms] fireEventAsync timeupdate
ogv.js:18 [306.3ms] fireEventAsync seeked
ogv.js:18 [307ms] initial seek to 0
ogv.js:18 [308.5ms] finishStartPlaying
ogv.js:18 [309ms] fireEventAsync play
ogv.js:18 [309.6ms] fireEventAsync playing
dialog-loader.js:57 Before Width:  969  Height:  1691
dialog-loader.js:66 After Width:  498  Height:  1686
ogv.js:18 [336ms] fireEvent seeking
ogv.js:18 [336.6ms] fireEvent timeupdate
ogv.js:18 [337.4ms] fireEvent seeked
dialog-loader.js:36 Dialog /Templates/wait-dialog.html closed.
ogv.js:18 [338.9ms] fireEvent play
ogv.js:18 [340.2ms] fireEvent playing
ogv.js:18 [340.9ms] canceling old processing timer
ogv.js:18 [342.1ms] prebuffering audio done; buffered to 0
ogv.js:18 [342.8ms] continuing at 0, -1
ogv.js:18 [343.5ms] play loop: playback reached end of data 0,0,0
ogv.js:18 [344ms] play loop: ENDING NOW: playback time -1; frameEndTimestamp: -1
ogv.js:18 [344.7ms] pausing at -1
ogv.js:18 [345.4ms] fireEventAsync pause
ogv.js:18 [346.1ms] fireEventAsync ended
ogv.js:18 [354.5ms] fireEvent pause
ogv.js:18 [355.7ms] fireEvent ended
playerViewModel.js:33 player.currentTime = -1currentTime=0.01
ogv.js:18 [357.1ms] requested seek to 0.01, mode exact
ogv.js:18 [357.9ms] pausing at -1
dialog-loader.js:57 Before Width:  498  Height:  1686
dialog-loader.js:66 After Width:  498  Height:  1703
ogv.js:18 [368.5ms] canceling old processing timer
ogv.js:18 [369.3ms] pausing at -1
ogv.js:18 [370.1ms] fireEventAsync seeking
ogv.js:18 [388.1ms] got input 0
ogv.js:18 [389ms] stream is at end!
ogv.js:18 [390ms] stream ended during linear seeking on audio
ogv.js:18 [391.1ms] fireEventAsync timeupdate
ogv.js:18 [392.1ms] fireEventAsync seeked
ogv.js:18 [393.3ms] initial seek to 0
ogv.js:18 [394.8ms] paused while in ready
ogv.js:18 [396.4ms] fireEvent seeking
ogv.js:18 [401.6ms] fireEvent timeupdate
ogv.js:18 [403.3ms] fireEvent seeked

**Comment by jseward311** [comment]
I have successfully piped the same file to a native video element with:
video.src = URL.createObjectURL(new Blob([ reader.result], {type: 'webm/video'}));

For some reason this same arrayBuffer will still not play when loaded into the OGV.js player.

**Comment by brion** [comment]
Are you doing an explicit seek to time 0 before play? I can confirm that it seems to go awry if I load it like this:

```js
document.querySelector('ogvjs').src = '/misc/bitrate.webm';
// ... wait until done ...
document.querySelector('ogvjs').currentTime = 0.0;
// ... wait until done ...
document.querySelector('ogvjs').play();
```

where it plays successfully if I leave out the seek, or if I run them all together in one invocation. Definitely looks like something wrong in that seek...

**Comment by brion** [comment]
Yeah it seems to be something in the linear seeking case where the file is very small. The demuxer hasn't returned packets yet at the time we see the stream as ended... I think I've got some condition checks wrong and it should do another round of data reads.

**Comment by brion** [comment]
f6b71486 fixes this on your test file for me; please confirm in your setup. :)

**Comment by jseward311** [comment]
Confirmed to work correctly with latest build.
