### ISSUE TITLE
Audio controls borked after updating to 1.6.0?

### ISSUE THREAD

**Issue by jseward311** [brion/ogv.js#517]
Just wondering if anyone else has experienced this issue. 
I have a volume slider, mute button and speed control. 
After the update to 1.6.0 all controls have stopped working. 
Audio still continues to play and seek properly. 

Will continue to investigate the cause.

**Comment by brion** [comment]
A lot of the setup for properties changed in 1.6.0, but should be doing the equivalent thing... The `mute` and `volume` properties are working for me; speed control would not have worked either before or after because it's not yet implemented.

**Comment by brion** [comment]
Might also double-check if there's a regression in a particular browser or version that I didn't catch... What browsers are you testing in?

**Comment by jseward311** [comment]
Browsers: Latest FF and Chrome
Speed Control: Custom implementation. (Work Around)

Seems this is the break:
        private.player.onaudiofeedercreated = function(audioFeeder) {
            private.audioProcessor.attachAudioFeeder(audioFeeder);
            public.channels = audioFeeder.channels;
        }

"ReferenceError: audioFeeder is not defined
    at eval (eval at PlayerViewModel.public.createPlayer (http://localhost:81/Scripts/App/ViewModels/playerViewModel.js:232:9), <anonymous>:1:1)
    at PlayerViewModel.public.createPlayer (http://localhost:81/Scripts/App/ViewModels/playerViewModel.js:232:9)
    at Object.WebPlayer.private.createPlayer (http://localhost:81/WebPlayer.js:421:33)
    at Emitter.<anonymous> (http://localhost:81/WebPlayer.js:108:25)
    at Emitter.emit (http://localhost:81/Scripts/Lib/emitter.js:134:20)
    at XMLHttpRequest.xhr.onload (http://localhost:81/WebPlayer.js:139:25)"

**Comment by brion** [comment]
Ah, I think I see it. The old `audioFeeder` var from inside the `OGVPlayer` constructor has been moved to `this._audioFeeder`. Should simplify your custom patch actually to not have to reach into the private vars manually. :D

**Comment by jseward311** [comment]
I take it there is no private.player.onaudiofeedercreated anymore?

**Comment by brion** [comment]
Doesn't look familiar; I assumed that was your custom hook point?

**Comment by jseward311** [comment]
Ah most likely. 
Just trying to get started on this refactor. 
cannot seem to hook up anything like before with 
private.player.audioFeeder

Or something of that nature.

**Comment by jseward311** [comment]
Yup found onaudiofeedercreated in the custom build stuff. Thanks I am going to close this. 

Might have more questions later though. Thank for the help.

**Comment by jseward311** [comment]
Is there a hook for when this._audioFeeder is ready?

**Comment by brion** [comment]
@jseward311 probably the best place to put one would be in the `_initAudioFeeder` method... Do you need to modify the AudioFeeder instance or replace it before/after creation? I could add a callback via the `options` array, just want to make sure I understand your use case before adding something so it works right. :)

**Comment by jseward311** [comment]
I am modifying audioFeeder after creation. This was initially for volume
control on each audio channel. And also to modify playback speed.

Before 1.6.0 I was adding the call back in before build. I had forgotten
this detail.

Trying to avoid any custom build stuff this time around.

**Comment by jseward311** [comment]
@brion 
Created pull request for onaudiofeedercreated callback.

https://github.com/brion/ogv.js/pull/519/commits/5f9592eadf0058220bb378bc5977bba60ab04bca

**Comment by jseward311** [comment]
Verified the call back works, thanks.
