### ISSUE TITLE
[Epic] MSE-based video/audio sink using uncompressed H.264, MP3

### ISSUE THREAD

**Issue by brion** [brion/ogv.js#520]
The current use of `<canvas>` and Web Audio/Flash for output is functional, but has a few downsides:
* no browser-provided default controls
* no prevention of screen dimming/locking if playback goes for a while
* the wrapper element isn't named `video` so CSS and JS selectors have to accommodate it specially
* no integration with browser features like picture-in-picture mode that are `<video>`-specific
* to use as a source for a canvas image draw or WebGL texture, must manually extract the `<canvas>`

A couple years ago I was pointed to ["the world's smallest h.264 encoder"](https://cardinalpeak.com/blog/worlds-smallest-h-264-encoder/) which produces uncompressed frames that can be decoded by any compliant h.264 encoder, but with no compression tricks so it may be more .... patent-friendly. ;)

It should be possible to use that technique to buffer up a few uncompressed h.264 frames as we're decoding, wrap them in fragmented MP4, and drop them into a Media Source Extensions buffer on an actual `<video>` element, at the relatively low cost of copying the buffer into little bits.

Audio sync would probably be best handled by running it through MSE as well. As far as I know no browser supports uncompressed audio in MSE, and Safari still doesn't support Opus. Best candidate is MP3, which is now patent-expired so a stock encoder can be used tuned to low-compression / high-bitrate, or a custom one can be tuned.

It should be possible to use the default controls by hooking various events to deal with the data input, just as you would with any other MSE-based video. I think?

It will not yet be possible to remove the old A/V sinks though, as iOS doesn't support MSE. This is a real shame, as iOS is the system I'd most like to target with the screen-lock problem!

**Comment by brion** [comment]
Only Safari and (pre-Chromium) Edge seem to support MP3 in MSE; Firefox and Chrome both have bugs in their trackers about it but don't work yet. Might want to look into whether AAC can be "hacked" into an uncompressed mode, or some other hack done...

**Comment by brion** [comment]
Looks like FLAC-in-MP4 works in Firefox, Chrome, and Edge (but not Safari). Can probably rig up MP3 for Safari and FLAC-in-MP4 for the rest. :D

**Comment by brion** [comment]
Making significant progress with this at https://github.com/brion/raw-to-mse though there are limits to compatibility.

**Comment by jseward311** [comment]
Is this work to also allow MP4 playback?

**Comment by brion** [comment]
It would allow for passing through compressed h.264 packets too yes, though I haven't pursued that yet.

**Comment by brion** [comment]
The compatibility problems for playing uncompressed frames are too extreme to get past I think (no ARM device I've found will play these frames, and most Windows devices only play up to 480p), though a variant of this technique for when you only need to transmux would be very interesting. I'll open a new issue for that later.
