### ISSUE TITLE
Does ogv.js provide the capability to resize the pixel dimension dynamically based on current encoded frame?

### ISSUE THREAD

**Issue by guest271314** [brion/ogv.js#531]
Given an input Matroska or WebM video produced by `MediaRecorder`, does ogv.js  provide the capability to resize the pixel dimension dynamically based on current encoded frame (currently does not occur at Chromium unless the codec is `avc1` or `h264`; see https://bugs.chromium.org/p/chromium/issues/detail?id=983777, https://github.com/web-platform-tests/wpt/issues/17821)? 

Have been attempting to set `src` of `<ogvjs>` element at demo https://brionv.com/misc/ogv.js/demo/#file=Curiosity's_Seven_Minutes_of_Terror.ogv&size=480p.webm at `console` though the one occasion was able to set the `src` did not observe any resize of the element and not sure if "Source:" affects output?

**Comment by brion** [comment]
The raw YUV output will use the native frame dimensions, and is scaled on the `<canvas>` output to match the specified aspect ratio (in the case of non-square pixels).

After file metadata is loaded, the `videoWidth` and `videoHeight` properties should update, and a `resize` event should be triggered. This may not happen immediately on setting src, you may have to trigger the `load` function. It also may not update the canvas until it's time to output, I'm not 100% sure.

See also https://github.com/brion/ogv.js/issues/354 -- if you're changing resolutions within a file, currently it should update but won't trigger `resize` events or update `videoWidth` and `videoHeight` props as it should, I think.

**Comment by guest271314** [comment]
Is there a test file demonstrating the output of ogv.js player output for variable input resolution? The use case is substituting ogv.js player for HTML `<video>` implementation at Chromium which has issues with variable resolution output. Mozilla Firefox and Nightly dispatch `resize` event for variable input encoded frames.

**Comment by guest271314** [comment]
Re #354 can you add the video https://raw.githubusercontent.com/brion/OGVKit/master/Example/Samples/vp8-res-switch.webm to the list of files at https://brionv.com/misc/ogv.js/demo/#file=Curiosity's_Seven_Minutes_of_Terror.ogv&size=360p.vp9.webm? 

The video linked video encoded with Lavf does resize when played back at Chromium, however when `captureStream()` is called on the element the tab crashes at the first `resize` event as described at https://bugs.chromium.org/p/chromium/issues/detail?id=983777#c22. 

Is the code used the produce the video available in JavaScript?
