### ISSUE TITLE
Demo bugs; ability to upload local test files?

### ISSUE THREAD

**Issue by guest271314** [brion/ogv.js#532]
At line 51 of https://brionv.com/misc/ogv.js/demo/demo.js?version=1.6.1-20190618150123-e65cc4a

`var data = JSON.parse(xhr.responseText);`

results in

```
Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.xhr.onreadystatechange (demo.js?version=1.6.1-20190618150123-e65cc4a:51)
```

Also, can an `<input type="file">` be added to the HTML for the ability to test ogv.js with local files?

**Comment by brion** [comment]
Yeah I have to clean this bit of the demo up and handle error cases better (or remove the remote calls when not actively searching entirely). Will take a peek in a bit.

You can drag-and-drop a file onto the video canvas to load from the local filesystem, but beware that not all browsers support seeking within a file loaded this way currently.

**Comment by brion** [comment]
Demo should be working now, I believe I fixed the breakage a bit ago. Still need to add a nicer UI for picking files though, so I'm changing the summary.
