### ISSUE TITLE
Help leveraging code for benchmarking standalone VM

### ISSUE THREAD

**Issue by jlb6740** [brion/ogv.js#536]
Hi,

I am looking in the /dist/ folder and wondering how to potentially leverage the wasm files for checking out performance of standalone wasm vms (no browser and no JS except if using node). I am not sure how to do this and am looking for any suggestions and pointers as I spend a little bit of time on this. In particular I am looking for SIMD examples and so I built with SIMD=1 though I can't seem to get wasm2wat --enable-simd to recognize the file ... I am hoping the files are valid. In any case, I've run your bench/benchmark.js through node and am looking to see if that can provide some inspiration but any other pointers are welcome. Thanks.

**Comment by brion** [comment]
Ah, this is an interesting thought. Currently the demuxer and decoder modules require JS glue code to run, both the general emscripten bits and the custom bits to queue up input and output.

There's two ways I would see to proceed:
1) use the existing ogv.js `.wasm` output and re-implement the import functions for each test VM environment
2) use the library builds and module wrappers, but plug them together on the C side and create a single build using emscripten's new "standalone" build support to minimize the external imports. You'd have C code replacing the JS library callbacks to feed data in/out.

For ensuring that data is correct -- always helpful! ;) -- the easiest thing is to run a checksum over the YUV buffers of output frames. I implement a CRC32 check in `demo/codec-bench.html` which I found very useful when tuning the SIMD code, as any minor mistake created a bad checksum even if it looked ok to the naked eye.
