### ISSUE TITLE
How to show player with controls?

### ISSUE THREAD

**Issue by AniketBhadane** [brion/ogv.js#539]
I'm using Angular 8. I want to play ogg audio in my browser.
In the browser, just the audio is being played without any controls (play/pause etc.)? 

My component ts file has:

```
  const ogv = require('ogv');

  @ViewChild('ogvContainer', { static: true }) ogvContainer: ElementRef;

  ogv.OGVLoader.base = '../../assets/js/ogv';
  let player = new ogv.OGVPlayer();
  this.ogvContainer.nativeElement.appendChild(player);
  let blob = new Blob([new Uint8Array(decodedData)]);
  player.src = URL.createObjectURL(blob);
  player.play();
```
My component html has:

` <div class="ogvContainer" #ogvContainer></div>`

Inside the ogvContainer div, another element is created.

```
<ogvjs class="ogvjs1" src="blob:http://localhost:4200/681e9637-5f93-4a0c-929e-678dd5e71529"> 
   <canvas style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; object-fit: contain;"></canvas>
</ogvjs>
```

But nothing is displayed. It just consumes empty space.

How can I show the player controls on UI?

**Comment by brion** [comment]
Controls are not yet included on the player code; you must provide your own. You might try video.js with the videojs-ogvjs plugin.
