### ISSUE TITLE
Using OGV to convert WEBM to OGG

### ISSUE THREAD

**Issue by AniketBhadane** [brion/ogv.js#540]
I have a case where I'm recording audio in Chrome which records in audio/webm; codecs=opus

But my server needs the audio to be in ogg container format.

Since ogv supports playback of both webm and ogg audio, can it convert webm to ogg?

**Comment by brion** [comment]
ogv.js includes a demuxer for WebM, but no muxers -- so you'd also need to add a muxer for the Ogg stream container, then send the packets from one to another.

**Comment by guest271314** [comment]
You can use https://github.com/Garciat/libvorbis.js, see https://jsfiddle.net/guest271314/rfoc42qt/.
