### ISSUE TITLE
update to opus 1.3.1

### ISSUE THREAD

**Issue by Brahmasmi** [brion/ogv.js#545]
Namaste Brion,

The current version for opus is 1.3.1 released in April 2019 [1]. Before that, 1.3.0 was released in October 2018 [2].

Cumulatively, these two versions have security and performance improvements over opus 1.2.1 [2] :

```
...
Improvements to stereo speech coding at low bitrate
Using wideband encoding down to 9 kb/s
Making it possible to use SILK down to bitrates around 5 kb/s
...
Security/hardening improvements
...
```

Dhanyavaad.
[1] - https://opus-codec.org/release/stable/2019/04/12/libopus-1_3_1.html
[2] - https://opus-codec.org/release/stable/2018/10/18/libopus-1_3.html

**Comment by daemoohn** [comment]
I think this is solved, as we migrated to a different submodule url.

**Comment by brion** [comment]
No, nothing has changed but the URL to the repo. It's still checked out at the `v1.2.1` version tag.

**Comment by brion** [comment]
Updating libraries now :D
