### ISSUE TITLE
Ogv with reactjs

### ISSUE THREAD

**Issue by Sibgha228** [brion/ogv.js#546]
I have followed this to play ogg file in my reactjs project using the .ogv library

First of all, put the library files to your React app. For the opus you will need:

ogv-demuxer-ogg.js
ogv-demuxer-ogg-wasm.js
ogv-demuxer-ogg-wasm.wasm
ogv-decoder-audio-opus.js
ogv-decoder-audio-opus-wasm.js
ogv-decoder-audio-opus-wasm.wasm
ogv-worker-audio.js
After that in your code:

Require the lib after all imports:

var ogv = require('ogv');
Set the base path for the files from the PUBLIC folder:

// process.env.PUBLIC_URL simply a ref for the root folder of the react app
ogv.OGVLoader.base = process.env.PUBLIC_URL + '/ogv'; 
Then you can use it as follows:

play = () => {
   var player = new OGVPlayer();
   // this.props.audioData just some audio data
   var blob = new Blob([new Uint8Array(this.props.audioData)]);
   player.src = URL.createObjectURL(blob);
   player.play();
}

I get the following error on console: 
**Error: WebAssembly.Module doesn't parse at byte 0: modules doesn't start with '\0asm' (ogv-demuxer-ogg-wasm.js, line 29)**

**wasm file doesn't loads.** I have tried on all browsers, getting the same result. Any idea on how to fix this ?

**Comment by brion** [comment]
Hmm, it sounds like either the path to the file is bad or the file is getting corrupted (maybe by something in webpack or whatever?) Can you check the "network" panel in developer tools to make sure the .wasm file loads correctly? Should not be a 404, and should have content-type application/wasm I think.

I haven't done much with react so I don't know the tools too closely...

**Comment by Sibgha228** [comment]
Yes thanks. So I was putting the files in the public folder but in ogv folder so I was getting a 404 there.
