### ISSUE TITLE
av1 not playing, did I encode it wrong?

### ISSUE THREAD

**Issue by Schizo** [brion/ogv.js#549]
Hi, I'm running an nginx server locally and the demo examples do work, so I wanted to create my own av1 formatted container and used the following command in ffmpeg:

```
 ffmpeg -i input.mov -map_metadata -1 -c:a libopus -c:v libaom-av1 -crf 34 -b:v 0 -pix_fmt yuv420p -movflags +faststart -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -strict experimental video.av1.mp4
```

However, that file doesn't seem to play, opening it in the browser through the url works (so file exists and is being served by nginx.)

Not sure if I'm to verbose here but to get a better picture, I've replaced the working version of  `minimal.html.in` from: 

```
function play(src) {
        player.src = 'media/llama-drama-av1.webm;
	player.play();
}
```
to
```
function play(src) {
	player.src = 'media/video.av1.mp4';
	player.play();
}
```

Any help appreciated. Can't, unfortunately, upload that file as it's copyrighted, but I'll try to create another reproducible case with a sample file.

**Comment by brion** [comment]
MP4 container is not yet supported; use WebM.

**Comment by Schizo** [comment]
That's simply it! Thanks for the hint.
