### ISSUE TITLE
Wasm streaming compile failed: TypeError Response has unsupported MIME type

### ISSUE THREAD

**Issue by Schizo** [brion/ogv.js#550]
Hi, I'm using the `minimal.html.in` and if I select ` 'media/llama-drama-av1.webm` I get the following message in my firefox/chrome console.

![image](https://user-images.githubusercontent.com/38006/75846895-7a7f6880-5d92-11ea-83c4-53455641a410.png)

Is that expected?

**Comment by brion** [comment]
This will happen if the web server isn't configured to sent the proper content-type header for .wasm files. It works but may be less efficient (worst case is a double download of the file). You may need to adjust the server config to send application/wasm.
