### ISSUE TITLE
Is Vorbis build currently failing?

### ISSUE THREAD

**Issue by Schizo** [brion/ogv.js#555]
I was able to build this repo by following the build instructions in the readme and after `npm install` it was working. However, since couple of days, it doesn't seem to work anymore. I even downgraded my emsdk to 1.38 just to be closer to the tested environment, that didn't help either.

I could narrow down the error, running these fails
```
bash ./buildscripts/configureVorbis.sh
bash ./buildscripts/compileVorbisJs.sh
```

**Error:**

'/Users/myuser/dev/GIT/emsdk/upstream/bin/clang -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=11 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystem/Users/myuser/dev/GIT/emsdk/upstream/emscripten/system/include/libcxx -Xclang -isystem/Users/myuser/dev/GIT/emsdk/upstream/emscripten/system/lib/libcxxabi/include -Xclang -isystem/Users/myuser/dev/GIT/emsdk/upstream/emscripten/system/lib/libunwind/include -Xclang -isystem/Users/myuser/dev/GIT/emsdk/upstream/emscripten/system/include/compat -Xclang -isystem/Users/myuser/dev/GIT/emsdk/upstream/emscripten/system/include -Xclang -isystem/Users/myuser/dev/GIT/emsdk/upstream/emscripten/system/include/libc -Xclang -isystem/Users/myuser/dev/GIT/emsdk/upstream/emscripten/system/lib/libc/musl/arch/emscripten -Xclang -isystem/Users/myuser/dev/GIT/emsdk/upstream/emscripten/system/local/include -Xclang -isystem/Users/myuser/.emscripten_cache/wasm/include -DHAVE_CONFIG_H -I. -I../../../../libvorbis/lib -I.. -I../../../../libvorbis/include -I/Users/myuser/dev/GIT/OGVtest1/ogv.js/build/js/root/include -DDARWIN -fno-common -force_cpusubtype_ALL -Wall -g -O3 -ffast-math -fsigned-char -Wdeclaration-after-statement -DUSE_MEMORY_H -MT psy.lo -MD -MP -MF .deps/psy.Tpo -c -DEMSCRIPTEN -fignore-exceptions ../../../../libvorbis/lib/psy.c -Xclang -isystem/Users/myuser/dev/GIT/emsdk/upstream/emscripten/system/include/SDL -c -o psy.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr' 

Not sure how I can pass `-v` to clang through emmake, that would yield some more, but If someone could verify that it is currently working, that would already help a lot.

Thanks

**Comment by yafesdev** [comment]
@Schizo Working fine for me as described in the `readme`. I'm on Ubuntu
