### ISSUE TITLE
npm install fails on compileVpxJs.sh using emscripten 1.39.13

### ISSUE THREAD

**Issue by brianjjones** [brion/ogv.js#560]
I get the following error when running 'npm install' on Ubuntu 18.04. I have SIMD=1 as well.

Requested extra CFLAGS '-s WASM=0 -DASMJS -I/home/bjones/GIT/WASM/emsdk/upstream/emscripten/system/lib/libcxxabi/include/' not supported by compiler

in build/js/libvpx/config.log I get:
clang-11: error: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Werror,-Wdeprecated]

I realize all these submodules and tools are probably constantly breaking each other's code, so is there a known configuration I should be using for building the demo? What version of emscripten, node, llvm, etc.

Thanks.

**Comment by brion** [comment]
Might be a change in the clang/LLVM version in the latest emscripten. I last built with 1.39.12 which is one version back, I think. 

Will take a peek tomorrow if I have a chance to see if I can fix the build on the latest.

**Comment by brianjjones** [comment]
Ah somehow that was the one version I didn't try, thanks. It does indeed build for me with 1.39.12.

**Comment by brion** [comment]
Ok got a chance to try this out and it looks like 1.39.14 also came out in the last few days. It's building successfully for me on macOS with 1.39.14 here, so .... hopefully that resolved the build regressions. ;) If you still see it fail on the latest version let me know and I'll double-check under Linux and see if I can figure out what's what.

**Comment by brianjjones** [comment]
It works for me as well, let me know if you'd like me to close this issue since its resolved.
