### ISSUE TITLE
The git.xiph.org seems to be down, can we change git submodule urls to github?

### ISSUE THREAD

**Issue by daemoohn** [brion/ogv.js#562]

**Comment by brion** [comment]
I'm working on fixing this now, been distracted sorry. ;)

**Comment by brion** [comment]
Ok, migrated the submodules from git.xiph.org (obsolete, down) to gitlab.xiph.org (new, works) :D

If you have trouble with git picking up the updated module sources, simplest thing is to re-clone the main repo and let it freshly clone the submodules from the new defs. :)

Thanks for the reminder!
