### ISSUE TITLE
Error on run-dev-server whiie working on demo

### ISSUE THREAD

**Issue by suman** [brion/ogv.js#563]
A) To run the demo, I executed the command **make run-dev-server** which generated the following error

> 0 info it worked if it ends with ok
> 	1 verbose cli [
> 	1 verbose cli   '/opt/emsdk/node/12.9.1_64bit/bin/node',
> 	1 verbose cli   '/opt/emsdk/node/12.9.1_64bit/bin/npm',
> 	1 verbose cli   'run',
> 	1 verbose cli   'server'
> 	1 verbose cli ]
> 	2 info using npm@6.10.2
> 	3 info using node@v12.9.1
> 	4 verbose stack Error: missing script: server
> 	4 verbose stack     at run (/opt/emsdk/node/12.9.1_64bit/lib/node_modules/npm/lib/run-script.js:155:19)
> 	4 verbose stack     at /opt/emsdk/node/12.9.1_64bit/lib/node_modules/npm/lib/run-script.js:63:5
> 	4 verbose stack     at /opt/emsdk/node/12.9.1_64bit/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
> 	4 verbose stack     at /opt/emsdk/node/12.9.1_64bit/lib/node_modules/npm/node_modules/read-package-json/read-json.js:418:5
> 	4 verbose stack     at checkBinReferences_ (/opt/emsdk/node/12.9.1_64bit/lib/node_modules/npm/node_modules/read-package-json/read-json.js:373:45)
> 	4 verbose stack     at final (/opt/emsdk/node/12.9.1_64bit/lib/node_modules/npm/node_modules/read-package-json/read-json.js:416:3)
> 	4 verbose stack     at then (/opt/emsdk/node/12.9.1_64bit/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
> 	4 verbose stack     at /opt/emsdk/node/12.9.1_64bit/lib/node_modules/npm/node_modules/read-package-json/read-json.js:364:12
> 	4 verbose stack     at /opt/emsdk/node/12.9.1_64bit/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:90:16
> 	4 verbose stack     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
> 	5 verbose cwd /var/www/html/ogv
> 	6 verbose Linux 5.6.6-300.fc32.x86_64
> 	7 verbose argv "/opt/emsdk/node/12.9.1_64bit/bin/node" "/opt/emsdk/node/12.9.1_64bit/bin/npm" "run" "server"
> 	8 verbose node v12.9.1
> 	9 verbose npm  v6.10.2
> 	10 error missing script: server
> 	11 verbose exit [ 1, true ]

B) For the same purpose, I ran another command  **npx webpack-dev-server**, this time the server is started, but the demo does not work, and it shows the message

>  ｢wds｣  webpack output is served from /
>  ｢wds｣: Content not from webpack is served from /var/www/html/ogv
>  
> 

C) Is there is any way that we can run the demo with expanded source code instead of minified version of JS files ?

**System information**
OS =>  Fedorat 32
nodeJs => v12.9.1
npm => 6.10.2

**Comment by tchakabam** [comment]
Hi @suman 

I'll only reply to point c) for now, as the answer is quick: 

I guess you'd  have to do *either* of these two:

* Enable source-maps ouput in webpack build config (and make sure your browser/runtime picks them up, i.e them being served properly under the same path)

* Disable minimization opt in webpack build (then build will be "exp

We should allow for options somehow by setting env vars probably ... ? 

PRs welcome I guess ;) 

About your points a) & b) I'd need to try out here with the latest version first

**Comment by tchakabam** [comment]
About the build system, I was able to do what you need with: 

```sh
npm install
make
npm start # run dev-server
```

Maybe the docs are a bit out-dated, but I am sure @brion get answer this more accurately.

**Comment by tchakabam** [comment]
About `make run-dev-server `, maybe you need to run plain `make` before, and also make sure to have `npm install`d. Not sure what else could be the issue here. 

It could be useful to sure your OS/version as well here to know.

**Comment by suman** [comment]
Hi Stephan,

Thanks for you reply,

A) make `run-dev-server` does not work because related script `npm run server` is not available in **package.json**. For this `make` command to work, we need to convert `npm run server` to `npm run start` on **Makefile**.

B) Question b was not any problem.

C) To run with the expanded JS code, I change `mode: production` to  `mode: 'development`, ' into **webpack.config.js**.

To run `git submodule update --init` command successfully, there is also need to change the urls in git submouldes file .

**Comment by brion** [comment]
Works for me on macOS 11.3.1. If it's still not working on current version, reopen with specifics of the operating system environment.
