### ISSUE TITLE
Are there improvements in this area that would allow us to keep the asm optimizations?

### ISSUE THREAD

**Issue by daemoohn** [brion/ogv.js#567]
https://github.com/brion/ogv.js/blob/089f80310d086a8c86dc60686c8380e421d20fb3/buildscripts/compileTheoraJs.sh#L21

**Comment by brion** [comment]
Not the existing asm which is assembler code for specific CPUs, no.

In theory one could write some SIMD optimizations and plug that into the asm config flag as I have done for AV1 decoding, but theora is already pretty fast.
