### ISSUE TITLE
Recommended encoding parameters

### ISSUE THREAD

**Issue by thenewguy** [brion/ogv.js#571]
Having trouble with vp8/vorbis playback using an iPhone 5 running iOS 10.3.4 as the target hardware for testing.  Using ogv.js version 1.6.1

Could you share your recommendations for settings that will generally play well on a wide variety of hardware?

Currently using 640x360 resolution at 365k for bitrate with 96k audio.  Frame rate is limited to 30 fps.  These are additional options passed to ffmpeg: pix_fmt yuv420p, profile:v 1, slices 2.  But the playback is not usable on the iPhone 5.

**Comment by brion** [comment]
Performance is most reliable on 64-bit devices, which are *much* faster and usually have more RAM. The iPhone 5 is a 32-bit device and I never had good results with it (though it was a bit faster than the older 32-bit models).

**Comment by thenewguy** [comment]
Ah bummer.  I will adjust our minimum hardware target then.

Would you recommend any tweaks to the encoding options?

**Comment by brion** [comment]
Sounds reasonable, if those don't run well on a 5S or later try bumping fps down to 24. Good luck! :)
