### ISSUE TITLE
Configurable url mapping in the Loader

### ISSUE THREAD

**Issue by thenewguy** [brion/ogv.js#572]
My environment includes a hash in static file names.

So the request for `ogv-demuxer-webm-wasm.js?version=1.6.1-20190618150123-e65cc4a` should really target `ogv-demuxer-webm-wasm.abc123.js?version=1.6.1-20190618150123-e65cc4a` or preferably just `ogv-demuxer-webm-wasm.abc123.js`

Is there currently a way to accomplish that?  [I didn't see it here](https://github.com/brion/ogv.js/blob/master/src/js/OGVLoaderBase.js#L65), so if not, would you merge and release a configurable mapper function if a suitable PR was provided?

**Comment by brion** [comment]
Currently no, you should use the file naming scheme arranged for and expected by the code.
