### ISSUE TITLE
Audio and fullscreen are not working with iPhone 5s

### ISSUE THREAD

**Issue by goffi-contrib** [brion/ogv.js#576]
Hello,

I've reported this on this old closed ticket: https://github.com/brion/ogv.js/issues/14
But it seems that my comment went unnoticed, so I'm putting this in a new ticket.

While video is playing correctly, Audio is not working with iPhone 5s (tested with local use + with official demo at https://brionv.com/misc/ogv.js/demo/). The fullscreen button is also not working.

Is this platform still supported? Is there something particular to do to make it work?

Thank you

**Comment by brion** [comment]
What iOS version? Should work still as far as I know if it's 11 or later

**Comment by brion** [comment]
(Please do not use old tickets, as they will not be noticed)

**Comment by goffi-contrib** [comment]
hello @brion , sorry for the late answer.
It's iOS version `12.4.6`.

**Comment by brion** [comment]
iOS 12 is out of support, and I cannot test it. No guarantees it will ever work.
