### ISSUE TITLE
No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by TechComet** [brion/ogv.js#580]
Hi,

Access to XMLHttpRequest at 'https://media-streaming.wmflabs.org/clean/transcoded/9/96/Curiosity%27s_Seven_Minutes_of_Terror.ogv/Curiosity%27s_Seven_Minutes_of_Terror.ogv.240p.vp9.webm' from origin 'https://brionv.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by brion** [comment]
That site is offline and no longer in use by the demo.
