### ISSUE TITLE
AV1 samples

### ISSUE THREAD

**Issue by arunetm** [brion/ogv.js#584]
We noticed that the recent changes drop the AV1 samples in favor of VP8/VP9 samples. Is AV1 no longer a representative use case? Can you help to understand the reasoning for this change?

**Comment by brion** [comment]
I accidentally deleted the VM with my sample files and have not yet recreated them. :)

I apologize for the inconvenience; if you use ffmpeg etc to produce AV1+Opus WebM files they should work.

**Comment by arunetm** [comment]
Thanks @brion. :)
