### ISSUE TITLE
S3 file duration problem

### ISSUE THREAD

**Issue by NumberI** [brion/ogv.js#585]
done:
player.src = some_link_to_s3_audio

result:
player.duration is NaN,
player.seekable.length = 0

S3 response has header 'Content-Range', not 'Range'

How it can be solved?

**Comment by brion** [comment]
To allow random access to a cross-site file, the CORS headers must be configured to allow:
* request header 'Range'
* response header 'Content-Range'

Without that, seeking is impossible and for files without an index, duration cannot be determined.

**Comment by brion** [comment]
closing but see https://github.com/brion/ogv.js/issues/591
