### ISSUE TITLE
Deprecation warning: ScriptProcessorNode

### ISSUE THREAD

**Issue by turbo** [brion/ogv.js#592]
The initialization based on an opus audio file throws a few warnings in Chrome, because (quoting [MDN](https://developer.mozilla.org/en-US/docs/Web/API/ScriptProcessorNode)):

> Note: As of the August 29 2014 Web Audio API spec publication, this feature has been marked as deprecated, and was replaced by AudioWorklet

The offending feature is used in the `initSharedAudioContext` method in ogv.

**Comment by brion** [comment]
Yeah I gotta speed up implementing the replacement on this... Warnings should be harmless for now.

The existing issue in the audio-feeder component is here, please subscribe to that to hear updates when I start working on it :) https://github.com/brion/audio-feeder/issues/37
