### ISSUE TITLE
Libvpx SIMD performance

### ISSUE THREAD

**Issue by ronniethelimodriver69** [brion/ogv.js#595]
Did you notice any performance increases with the SIMD build for the VP9 decoder?  I’m getting about the same performance as non-SIMD, but I also enabled high bit depth when compiling libvpx. Thanks.

**Comment by brion** [comment]
Only very slight, and only where I'd specifically added code for it, which is only a small number of places. I'm not going to continue working on the SIMD Wasm decoder code, though, as Apple isn't supporting SIMD for Wasm as far I know but they are rolling out native VP9 decoding.

**Comment by ronniethelimodriver69** [comment]
Thanks for your quick reply!
