### ISSUE TITLE
iOS only | Weird issue video not playing in video.js but does if native player is also started

### ISSUE THREAD

**Issue by Hideman85** [brion/ogv.js#596]
Hi @brion I'm still investigating what issue I having with the video playing on iOS and this is very strange.

Taking [my sample](https://codepen.io/Hideman85/pen/GRExVGN?editors=1000) I really do not understand what is going on and really need your help on this.

**Simple video of the issue:**
![Video](https://user-images.githubusercontent.com/16165119/134700803-7515b278-8e43-485f-a9db-12030d1f7808.mp4)

**Reproduction:**

Use that link for the preview only on mobile https://codepen.io/Hideman85/full/GRExVGN

- First case:
  - Click on "Play videojs"
  - Then start the video on the player
    - The video does not play but you can seek and get the frame decoded
- Second case:
  - Refresh the page
  - Click on "Play native"
    - The native element only is added and the video plays normally
  - Click on "Play videojs"
  - Then start the vide on the player
    - The video somehow is playing well too

What do you think could cause this weird behavior? And why only on iOS safari & chrome (desktop safari is playing fine, desktop chrome & firefox fine too and android is also fine)

I would really appreciate some light on that issue.

Thank you in advance.

**Comment by Hideman85** [comment]
Hi @brion, sorry for "spamming" but I really need some help on this, our clients depends on your feedback.
I dug down into the library, but I really don't get what can causing this issue.

**Comment by Hideman85** [comment]
Hi @brion hope you're well, I'm wondering if you had a look to that issue, fortunately we don't have that much users using it on non supported devices but it has be reported to us multiple time and we need to get back to them.

**Comment by brion** [comment]
Sorry, I can't reproduce your bug. It plays fine on my iPhone 13 and my iPhone X.

**Comment by Hideman85** [comment]
The videojs player is working for you? I would need to have a look again but I remember when I tried it was 50/50 and we got multiple of our client complaining it does not work :slightly_frowning_face: 
I would love to know what we could do for solving this issue currently we abandoned this feature because of the stability
