### ISSUE TITLE
Feature REQ | Ability to encode in VP9/opus/webm using that library

### ISSUE THREAD

**Issue by Hideman85** [brion/ogv.js#597]
A very nice feature would be to be able to encode also using this library. I do not know how much work need to be done for having that feature but it would be super nice to close the gap of also recording video on MacOS Safari & iOS.

A very good library that I'm using for playing & recording is video.js with in addition videojs-record.

**Comment by brion** [comment]
merging into old https://github.com/brion/ogv.js/issues/56 :D
