### ISSUE TITLE
How to set up appropriate CORS headers to allow loading of the worker JS modules ?

### ISSUE THREAD

**Issue by HorbachAndrii** [brion/ogv.js#598]
Can't download `ogv-demuxer-webm-wasm.wasm`, but this `ogv-demuxer-webm-wasm.js` was download 

![image](https://user-images.githubusercontent.com/36758882/134723248-fdc9bd9b-6fd2-455c-a954-8cbc671f1821.png)

How to set up appropriate CORS headers to allow loading of the worker JS modules? 
Can you give some example?

**Comment by HorbachAndrii** [comment]
Will be great if will be exist a way to manual load the worker JS modules

**Comment by Hideman85** [comment]
For the CORS issue this is relative to your hosting configuration not the library itself. That mean you need to enable CORS on the OVG and sub dirs in your hosting site.

Note if you want to play a video, this video also needs to be serve via a hosting with CORS enabled (+ from my experience you have to add Content-Range to the allowed cors headers as a response of the server)

Hope this helps, if you want for the library you can use a fallback on a CDN version (CORS enabled by nature) like [jsdelivr](https://www.jsdelivr.com/package/npm/ogv) and have a look to that [CodePen](https://codepen.io/Hideman85/pen/eYWNKQV?editors=1010) for the usage.
