### ISSUE TITLE
No sound on iPhone with silent mode enabled

### ISSUE THREAD

**Issue by iamCristYe** [brion/ogv.js#600]
Recently I found out that I must use headphones or disable silent mode on iPhone to listen to ogg files on [Moodle](https://tracker.moodle.org/browse/MDL-65943). I then realized that this is an upstream issue with ogv.js. This issue can be reproduced by visiting the ogv.js demo page: https://brionv.com/misc/ogv.js/demo/

1. visit the demo page with an iPhone
2. enable [silent mode](https://support.apple.com/en-hk/HT208353)
3. start the video, there's no sound even if you turn the media volume to max
4. disable silent mode, immediately you can hear the sound.

For your reference, I'm using iOS 14.8

**Comment by kelson42** [comment]
@iamCristYe Thank you very much for this bug report. I have been suffering from this bug since years with Kiwix on iOS and ZIM files with videos. We were not smart enough to identify the pattern like you did. I just have tested on my iPad with iOS 15.1 and I can confirm: I have the very same bad behaviour.

**Comment by iamCristYe** [comment]
https://github.com/processing/p5.js/issues/3907
https://stackoverflow.com/questions/21122418
https://stackoverflow.com/questions/40789136

Looks like the problem is related to the behavior of Web Audio API on iPhone. The stackoverflow thread provides a workaround, could you please try if that works? Thanks!

**Comment by brion** [comment]
I'll take a look at this in triage, thanks for the reports! Recommended workaround seems to be to run a silent HTML5 `<audio>` tag in the background, which should be pretty easy to arrange, and may actually be advantageous for control purposes.

**Comment by thenewguy** [comment]
I encountered this today on a test iPhone - took awhile to figure out as I didn't even know there was such a thing as a hardware toggle switch for silence =P

**Comment by hartman** [comment]
I filed an upstream ticket with Apple for this problem https://bugs.webkit.org/show_bug.cgi?id=237322

**Comment by kelson42** [comment]
@brion Thx!!!
