### ISSUE TITLE
How to add controls in the player

### ISSUE THREAD

**Issue by ParulChak** [brion/ogv.js#601]
I am using the cdn for this player, but having some issue while adding the controls in it.

`  <script async="" src="https://cdn.jsdelivr.net/npm/ogv@1.8.4/dist/ogv.js"></script>`

Now video is coming in playing mode without any control

Can anyone, explain me how to add controls(play, pause, mute, progress bar, autoplay, etc.) in it

**Comment by brion** [comment]
Controls are not implemented at this time, you must add them yourself with HTML. You can use frameworks like video.js for this if you like.
