### ISSUE TITLE
Please create demo of just audio playing with ogg formatted data

### ISSUE THREAD

**Issue by zackees** [brion/ogv.js#602]
I'm trying to just play ogg and using ogv.js as a polyfill. It would be nice to have just a simple site that shows audio decoding for an <audio> tag.

Thanks

**Comment by brion** [comment]
check out `minimal.html` in the demo player. video is same as audio for most intents and purposes.

**Comment by zackees** [comment]
Yeah, i can't get it to work.
  * `git clone https://github.com/brion/ogv.js`
  * `cd ogv.js/demo`
  * `mv minimal.html.in minimal.html`
  * `python -m http.server`
  * open up web browser to http://localhost:8000

I get tons of errors.

I don't get it. You guys did all this work to port the library. Why not just have a simple self contained demo?

MORE: Oh I looked through the documents and I have to have mac/linux and I have to do an entire build. Lol, just have a demo.
