### ISSUE TITLE
MediaRecorder Blob in safari throwing error

### ISSUE THREAD

**Issue by raisonjoseph** [brion/ogv.js#616]
I was trying to record audio through MediaRecorder API. The Blob file it returns has type `auido/mp4`. When I try to play the Blob with ogv.js it gives me an error 

```
Unhandled Promise Rejection: NotAllowedError: 
The request is not allowed by the user agent or the platform in the current context, 
possibly because the user denied permission.
```

Thanks in advance

**Comment by brion** [comment]
ogv.js does not support any media with an mp4 container at this time. Also you seem to have a user permissions error.
